### ISSUE TITLE
Which part of cod  is responsible for Checking which patches are installed at a remote windows machine?

### ISSUE THREAD

**Issue by henrikalmeida** [greenbone/openvas-scanner#1007]
I cannot find which part of its source codes is responsible for checking which patches are installed on a remote machine, and whether or not the system is vulnerable or not based on the windows build number and the installed patches?

**Comment by ArnoStiefvater** [comment]
Hello,

This is not a bug issue but a support question.

Maybe you want to look at the nasl scripts which are responsible for vulnerability detection. They are synced with the greenbone-nvt-sync script and not part of the openvas-scanner.

If you need further support please join / post at https://community.greenbone.net () as this tracker is only used for reporting / handling bugs.
