### ISSUE TITLE
Where can i find the vulnerlability (CVE/KB) database?

### ISSUE THREAD

**Issue by henrikalmeida** [greenbone/openvas-scanner#1008]
I cannot find where is the database of CVEs and their corresponding KB to fix them (obviously it will be different KBs based on windows version). is?

So where can i find this? I am mainly concerned with Windows vulnerlabilites that have CVE and a corresponding KB.

**Comment by ArnoStiefvater** [comment]
Hello,

This is not a bug issue but a support question.

Maybe https://docs.greenbone.net/GSM-Manual/gos-21.04/en/managing-secinfo.html#secinfo has the info you need.

If you need further support please join / post at https://community.greenbone.net as this tracker is only used for reporting / handling bugs.
