### ISSUE TITLE
/etc/openvas/openvas.conf path changed from install-prefix to /etc?

### ISSUE THREAD

**Issue by kees-closed** [greenbone/openvas-scanner#1011]
In the [documentation](https://github.com/greenbone/openvas-scanner/blob/main/INSTALL.md?plain=1#L151) it's stated that the install-prefix is used. However, in 21.4.3 it seems that /etc/openvas is used? This is different behavior compared to 21.4.0, which my container was using, and where the install-prefix directory (/usr/local/etc/openvas/) existed after `make install`. Now it only seems to make `/etc/openvas`, so I guess this has changed? Could you please update your documentation if this is the case?

Also `/usr/local/var/lib/openvas` is now in `/var/lib/openvas`? I'll update my container, but if this is not intended, then please be aware of this. The default install-prefix should be `/usr/local` according to the [docs](https://github.com/greenbone/openvas-scanner/blob/main/INSTALL.md?plain=1#L70). For some reason `/usr/local/share/openvas` is still where it should be. This seems inconsistent and my guess is that this is unintended.

**Comment by cfi-gb** [comment]
The default has been indeed changed in #826 in the past. There is already an open MR since a few weeks to update the related documentation in #826

**Comment by kees-closed** [comment]
Thanks for clearing that up! Then I'll set the prefix myself to /usr/local again.

**Comment by kees-closed** [comment]
It seems it's still a half finished change? At least when I remove all the /usr/local prefixes it doesn't work. When I add my own build flags to explicitly use /usr/local it doesn't work. There are still some parts using /usr/local when `-DCMAKE_INSTALL_PREFIX=/usr/local/` is not set. I'm still troubleshooting. The previous situation was much more predictable and "just worked".

Just to confirm, by setting `-DCMAKE_INSTALL_PREFIX=/usr/local/` some paths are still using system default paths such as /run, /var/lib, /var/log and paths like that? It would've been nice if the `-DCMAKE_INSTALL_PREFIX=/usr/local/` is set, everything is put relatively to /usr/local e.g. /usr/local/var/lib.

**Comment by ArnoStiefvater** [comment]
Yes, some paths are used which are not in the CMAKE_INSTALL_PREFIX.

If you want to have everything in the CMAKE_INSTALL_PREFIX as before you can do:
`cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DSYSCONFDIR=$INSTALL_PREFIX/etc   -DLOCALSTATEDIR=$INSTALL_PREFIX/var  -DOPENVAS_RUN_DIR=$INSTALL_PREFIX/run/ospd ..`
