### ISSUE TITLE
CMake Error: The source directory "/source" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by MohandesaliRahnema** [greenbone/openvas-scanner#1015]
cd ./.docker
docker build -t openvas prod.dockerfile
==================res==================
CMake Error: The source directory "/source" does not appear to contain CMakeLists.txt.

**Comment by y0urself** [comment]
You need to build the docker file from the source/root directory, not from the `.docker` directory.
The context than needs to be the root directory, not the `.docker` directory.
E.g.:  
`docker build -t test-openvas .docker/prod.Dockerfile .`

**Comment by y0urself** [comment]
You can also just pull the docker image from [docker hub](https://hub.docker.com/r/greenbone/openvas-scanner) instead of building it by yourself.
e.g.: `docker pull greenbone/openvas-scanner`
