### ISSUE TITLE
21.4.4: confusion about newly introduced libnet dependency

### ISSUE THREAD

**Issue by tgurr** [greenbone/openvas-scanner#1043]
`nasl/CMakeList.txt` has `${LIBNET_LDFLAGS}` in `target_link_libraries` but is missing the whole find_library depedency check from https://github.com/greenbone/openvas-scanner/commit/7503c8c5d420a7bb74fae7ad2eeb6eb0c83421d1.

additionally it seems to carry https://github.com/greenbone/openvas-scanner/commit/41729b2acbe6f7ded9f567c5124a73fc081fce58 which implicates the libnet dependency was already removed again with https://github.com/greenbone/openvas-scanner/commit/6d3a797dc0babb15faa5fd65b1ff2f600f0cf30b, however git main branch also still has the  `${LIBNET_LDFLAGS}` in `target_link_libraries` so apparently not completely?

Consider me confused.

**Comment by jjnicola** [comment]
Hey @tgurr ! 
thanks for reporting. I added libnet and then It was not required anymore with the next PR. It seems I forgot to clean the cmake. Will take a look.
