### ISSUE TITLE
docs: typo in the readme's docker section results in deadlink/404

### ISSUE THREAD

**Issue by redtux** [greenbone/openvas-scanner#1144]
Hi everybody,

There is a small typo in the [readme's docker section](https://github.com/greenbone/openvas-scanner#docker-greenbone-community-containers):

The link at [line 40 of README.md](https://github.com/greenbone/openvas-scanner/blob/main/README.md?plain=1#L40) should point to [docs/latest/21.4/container/](https://greenbone.github.io/docs/latest/21.4/container/) (or to [docs/latest/22.4/container/](https://greenbone.github.io/docs/latest/22.4/container/)).

So the version number `21.04` in the link needs to be changed to `21.4` (or `22.4`) accordingly.

**Comment by ArnoStiefvater** [comment]
Hello,

Thanks for reporting the issue. The links are fixed now for the main(22.4) and stable(21.4) branches.
