### ISSUE TITLE
openvas-nasl doesn't work properly

### ISSUE THREAD

**Issue by dvppvd** [greenbone/openvas-scanner#1251]
### Expected behavior
`openvas-nasl` works properly.

### Actual behavior
When running the VT `find_service.nasl` with `openvas-nasl`, no services are detected, running with `openvas` is fine.

### Steps to reproduce

1. Run the VT `find_service.nasl` against a host with `openvas-nasl`.
2. Notice that no services are detected.

### GVM versions
**ospd-openvas:** built from latest stable source (HEAD: 71e568611201556b404c46de15c26bae75cb457a).

**Note**: the tool worked properly in the previous versions such as v22.4.0.

**Comment by cfi-gb** [comment]
@dvppvd This info was missing so far that a previous version of `openvas-nasl` worked. Could you please add this info to the initial report so that the team working on this topic is able to see that immediately.
