### ISSUE TITLE
[22.5.0]  nasl-cli-x86_64-unknown-linux-gnu.asc looks broken

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#1391]
+ /usr/lib/rpm/redhat/gpgverify --keyring=/builddir/build/SOURCES/GBCommunitySigningKey.asc --signature=/builddir/build/SOURCES/nasl-cli-x86_64-unknown-linux-gnu.asc --data=/builddir/build/SOURCES/nasl-cli-x86_64-unknown-linux-gnu
gpgv: not a detached signature
gpgverify: Signature verification failed.

**Comment by nichtsfrei** [comment]
Thanks, updated the asc for the files.
