### ISSUE TITLE
openvas fails to compile on clang 15+

### ISSUE THREAD

**Issue by igalic** [greenbone/openvas-scanner#1403]
despite fixes in https://github.com/greenbone/openvas-scanner/pull/1025 clang 15+ still reports issues. this was originally reported as: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270464

### Expected behavior

Build succeeds

### Actual behavior

build fails:

```
misc/CMakeFiles/openvas_misc_shared.dir/plugutils.c.o -MF misc/CMakeFiles/openvas_misc_shared.dir/plugutils.c.o.d -o misc/CMakeFiles/openvas_misc_shared.dir/plugutils.c.o -c /wrkdirs/usr/ports/security/openvas/work/openvas-scanner-22.4.0/misc/plugutils.c
/wrkdirs/usr/ports/security/openvas/work/openvas-scanner-22.4.0/misc/plugutils.c:841:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
plug_get_key_sigchld ()
                     ^
                      void
1 error generated. 
```

### Steps to reproduce

1. install llvm 15+
2. attempt to build
3. build fails

### Environment

**Operating system:**

see https://portsfallout.com/fallout?port=security%2Fopenvas%24 for all the FreeBSD versions where this fails

**Comment by igalic** [comment]
thanks!

**Comment by jjnicola** [comment]
> thanks!

Thank you for reporting.
Regards.
