### ISSUE TITLE
Debian Bookworm  - libudev1 unmet dependencies

### ISSUE THREAD

**Issue by maximlomans** [greenbone/openvas-scanner#1404]
Im on Debian bookworm /ParrotSec rolling dist

6.1.0-1parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Parrot 6.1.15-1parrot1 (2023-04-25) x86_64 GNU/Linux

not exctly a GVM issue  

https://packages.debian.org/bookworm/libudev1 
-->

### GVM versions
upgrade broke setup 

apt show openvas
Package: openvas
Version: 21.4.4+parrot1
Priority: optional
Section: oldlibs
Source: gvm
Maintainer: Debian Security Tools <team+pkg-security@tracker.debian.org>
Installed-Size: 13.3 kB
Depends: gvm
Homepage: https://www.greenbone.net/
Download-Size: 5,332 B
 .
 

$ apt show libudev1
Package: libudev1
Version: 252.5-2~bpo11+1
Priority: optional
Section: libs
Source: systemd
Maintainer: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
Installed-Size: 245 kB
Depends: libc6 (>= 2.30)
Homepage: https://www.freedesktop.org/wiki/Software/systemd
Download-Size: 108 kB
APT-Manual-Installed: yes

### Steps to reproduce 
tried compiling version 22.5 got stuck on dependencies ;

$:  sudo apt-get install gcc pkg-config libssh-gcrypt-dev libgnutls28-dev libglib2.0-dev libjson-glib-dev libpcap-dev libgpgme-dev bison libksba-dev libsnmp-dev libgcrypt20-dev redis-server libbsd-dev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gcc is already the newest version (4:10.2.1-1).
gcc set to manually installed.
pkg-config is already the newest version (0.29.2-1).
libpcap-dev is already the newest version (1.10.3-1~bpo11+1).
libpcap-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libudev-dev : Depends: libudev1 (= 247.3-7+deb11u2) but 252.5-2~bpo11+1 is to be installed
E: Unable to correct problems, you have held broken packages.

i'm considering reinstalling 21.4 since docker build will most likely glitch too

**Comment by cfi-gb** [comment]
If there are still issues about package dependencies in the future please note that Greenbone doesn't maintain any distribution packages (responsible for such dependencies like libudev1 and these would need to be reported to the package maintainer (here Parrot and/or Debian).

**Comment by ArnoStiefvater** [comment]
Also some additional information because you linked some 3rd party install instructions.
We have an official install instruction at https://greenbone.github.io/docs/latest/ if you want to install from source.
We also have video for installing the Greenbone Community Edition from Docker Containers.
