### ISSUE TITLE
huge error in the code or gvm  or  OpenVAS Scanner version mismatch error in GVM-22.4.1 / ERROR: OpenVAS Scanner too old or too new: 22.6.2~git-68bf4de1-main

### ISSUE THREAD

**Issue by kishwordulal1234** [greenbone/openvas-scanner#1422]
Description:
I am experiencing an issue with the GVM-22.4.1 installation on my system. When running the "gvm-check-setup" command, I am getting an error message that says "OpenVAS Scanner too old or too new: 22.6.2~git-68bf4de1-main", even though I have tried downgrading and re-installing the OpenVAS Scanner multiple times.

Steps to Reproduce:

    Install GVM-22.4.1 on a system.
    Run the "gvm-check-setup" command.

Error Result:
ERROR: OpenVAS Scanner too old or too new: 22.6.2~git-68bf4de1-main
Full error :
┌──(unknonehart㉿unknnonehart)-[~]
└─$ sudo gvm-check-setup
[sudo] password for unknonehart: 
gvm-check-setup 22.4.1
  Test completeness and readiness of GVM-22.4.1
Step 1: Checking OpenVAS (Scanner)... 
        ERROR: OpenVAS Scanner too old or too new: 22.6.2~git-68bf4de1-main
        FIX: Please install OpenVAS Scanner >= 22.4.

 ERROR: Your GVM-22.4.1 installation is not yet complete!

Please follow the instructions marked with FIX above and run this
script again.

                                                         

steps taken by me to solve this by my self :
1923  sudo openvas-setup\n
 1924  sudo apt-get install greenbone-security-assistant\n
 1927  sudo systemctl stop postgresql\n
 1929  dpkg -l postgresql*\n
 1930  sudo -u postgres psql
 1933  sudo -u postgres postgres --single -D /var/lib/postgres/data/\n
 1934  sudo -u postgres psql\n
 1935  sudo systemctl start postgresql\n
 1936  msfdb init
 1937  sudo msfdb init
 1938  sudo service metasploit restart\n
 1940  cat config/database.yml
 1941  nano config/database.yml
 1942  bin/rails db:create
 1943  msfdb db_create\n
 1944  sudo  msfdb db_create\n\n
 1946  bundle install
 1947  gem 'activerecord', '6.1.4'\n
 1948  gem uninstall activerecord -v 6.1.7.3\n
 1949  sudo gem uninstall activerecord -v 6.1.7.3\n
 1950  gem list activerecord --user-install\n
 1951  gem uninstall activerecord -v 6.1.7.3 --user-install\n
 1952  gem install pg
 1953  bundle update pg
 1954  sudo service metasploit stop\n
 1957  msfconsole
 1959  sudo rm -r venom1
 1961  sudo su
 1963  sudo gvm-setup
 1964  xset led off
 1966  cd /usr/local/share/bettercap/
 1968  sudo rm -r caplets
 1970  git clone https://github.com/bettercap/caplets.git
 1971  sudo git clone https://github.com/bettercap/caplets.git
 1973  cd capletes
 1975  cd caplets 
 1978  sudp apt-get install gvm
 1980  sudo apt list --installed | grep openvas-scanner\n
 1981  sudo add-apt-repository ppa:gvm-ubuntu/gvm-20\n
 1984  sudo apt-get remove openvas-scanner\n
 1985  sudo apt-get install faraday-agent-dispatcher gsad gvm gvm-tools gvmd kali-tools-vulnerability openvas openvas-scanner ospd-openvas python3-gvm\n\n
 1986  gvm-cli --version\n
 1987  ls
 1988  sudo useradd -r -M -U -G sudo -s /usr/sbin/nologin gvm
 1989  sudo apt-get install openvas\n
 1990  sudo systemctl start openvas-scanner\n
 1991  gvm-setup
 1992  sudo su 
 1993  xset led on
 1994  sudo gvm-check-setup\n
 1995  openVAS --version
 1996  openvas-scanner --version\n
 1997  sudo su 
 1998  sudo apt-get update && sudo apt-get upgrade
 1999  sudo apt-get install gvm
 2000  sudo apt-get install openvas\n
 2001  sudo gvm-check-setup\n
 2002  sudo gvm-setup\n
 2003  sudo gvm-check-setup\n
 2004  sudo apt-get install openvas-scanner=22.4.1\n
 2005  sudo apt list --installed | grep openvas-scanner
 2006  sudo apt-get install gvm-libs gvm-tools openvas9
 2007  sudo systemctl restart openvas-scanner.service && sudo systemctl restart gvmd.service && sudo systemctl restart ospd-openvas.service
 2008  sudo apt-get install gvm-tools
 2009  sudo apt-get install openvas-scanner\n
 2010  sudo systemctl restart openvas-scanner.service && sudo systemctl restart gvmd.service && sudo systemctl restart ospd-openvas.service
 2011  sudo gvm-check-setup
 2012  wget -q -O - http://deb.gvmtool.net/GPG-KEY-gvm | sudo apt-key add -
 2013  sudo apt-get install openvas-scanner\n
 2014  sudo apt-get upgrade gvm
 2015  sudo gvm-check-setup
 2016  sudo apt-get remove openvas-scanner\n
 2017  echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list.d/kali.list\n
 2018  sudo apt-get update\n
 2019  sudo apt-get install openvas-scanner=22.4.*\n
 2020  sudo systemctl restart openvas-scanner.service
 2021  sudo systemctl restart gvmd.service
 2022  sudo systemctl restart ospd-openvas.service
 2023  gvm-check-setup
 2024  sudo gvm-check-setup
info:
i tried every thing that is possible to fix it i downloaded its files from repository and try to fix it it dident worked and i that i need to install fresh Kali i tried that it also dident worked facing same error and i tried downgrading it it also dident worked i try editing its config file it dident worked watched dozen of video to fix it dident worked took help of max 6 ai they ware also not able to fix this error now i am tired of this so i left i am working for it since 3 weeks and now i am totally ne-notch to fix this now you gyes can help me to fix this please contact me soon 

Additional Information:

    The system is running on Kali Linux 2023.1.
    I have tried downgrading the OpenVAS Scanner to version 22.4.*, but the error message persists.
    I have also tried uninstalling and re-installing the GVM-22.4.1 package, but the error message still persists.
    The error message suggests that the OpenVAS Scanner version is either too old or too new. However, I have verified that the version of the OpenVAS Scanner installed on my system is 22.4.2, which should be compatible with GVM-22.4.1.

I would appreciate any help in resolving this issue. Thank you.
![Screenshot from 2023-05-12 07-03-48](https://github.com/greenbone/openvas-scanner/assets/86870658/12b58173-529c-4f3e-bd5c-2a82526f2ff1)
![Screenshot from 2023-05-10 22-57-41](https://github.com/greenbone/openvas-scanner/assets/86870658/a0236147-08a8-41bb-a66b-f0a4a0830c31)

**Comment by kishwordulal1234** [comment]
docker is also not working  2017 version is working latest version is not working i try to open localhost and it saya unable to connect

**Comment by cfi-gb** [comment]
Hello,

please use https://forum.greenbone.net/ for support requests as stated in https://github.com/greenbone/openvas-scanner#support

As a side-note: `gvm-check-setup` isn’t maintained by Greenbone and might report things falsely / not fully correct

**Comment by y0urself** [comment]
> ![Screenshot from 2023-05-12 07-36-43](https://user-images.githubusercontent.com/86870658/237854405-c0141afa-6a63-4928-bd30-7e8904f80903.png)
> 
> ![Screenshot from 2023-05-12 07-48-15](https://user-images.githubusercontent.com/86870658/237854373-f774a6f4-1c48-4396-9ad6-750325685b9c.png)
> 
> docker is also not working 2017 version is working latest version is not working i try to open localhost and it saya unable to connect

This docker version is not from us. If you want support using docker, please follow our [documentation](https://greenbone.github.io/docs/latest/22.4/container/index.html), if there occurs any problems, please do what @cfi-gb mentioned.

We are not the creator of the `gvm-check-setup` tool you mentioned, which belongs to Kali Linux. AFAIK there are a lot of problem solving in our forum. When you want to build our software from source and need help, I again would refer you to the [documentation](https://greenbone.github.io/docs/latest/22.4/source-build/index.html) of source building.

**Comment by cfi-gb** [comment]
@kishwordulal1234 In short:
- the issue was not deleted but closed because this is not a support channel for setup issues
- community based support / help is still offered at https://forum.greenbone.net
