### ISSUE TITLE
 ERROR: redis-server is not running or not listening on socket: /var/lib/redis/redis.sock

### ISSUE THREAD

**Issue by bappa92chakraborty** [greenbone/openvas-scanner#145]
Hi I got this redis-server Issue please Kindly help me, Iam using Kali linux 2018.1. 

#openvas-check-setup
openvas-check-setup 2.3.7
  Test completeness and readiness of OpenVAS-9
  (add '--v6' or '--v7' or '--v8'
   if you want to check for another OpenVAS version)

  Please report us any non-detected problems and
  help us to improve this check routine:
  http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss

  Send us the log-file (/tmp/openvas-check-setup.log) to help analyze the problem.

  Use the parameter --server to skip checks for client tools
  like GSD and OpenVAS-CLI.

Step 1: Checking OpenVAS Scanner ... 
        OK: OpenVAS Scanner is present in version 5.1.1.
        OK: redis-server is present in version v=4.0.10.
        OK: scanner (kb_location setting) is configured properly using the redis-server socket: /var/lib/redis/redis.sock
        ERROR: redis-server is not running or not listening on socket: /var/lib/redis/redis.sock
        FIX: You should start the redis-server or configure it to listen on socket: /var/lib/redis/redis.sock

 ERROR: Your OpenVAS-9 installation is not yet complete!

Please follow the instructions marked with FIX above and run this
script again.

If you think this result is wrong, please report your observation
and help us to improve this check routine:
http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
Please attach the log-file (/tmp/openvas-check-setup.log) to help us analyze the problem.

**Comment by bjoernricks** [comment]
Sorry, the issue tracker is not a support forum. Please try to ask on http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
