### ISSUE TITLE
Hello, if I want to translate the scanner results, I should translate the .nasl file. Rebuild?

### ISSUE THREAD

**Issue by hellozhuzhu** [greenbone/openvas-scanner#147]
Hello, if I want to translate the scanner results, I should translate the .nasl file. Rebuild?Can I do this?

**Comment by jjnicola** [comment]
Hello @hellozhuzhu,
Sorry, the issue tracker is not a support forum. The question is proper for the openvas-discuss mailing list http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss.
Close issue here.
