### ISSUE TITLE
Failed to sync the feed (openvas-feed-sync)

### ISSUE THREAD

**Issue by himuura** [greenbone/openvas-scanner#148]
Hi there! Don't know if this is the right place and i'm terribly sorry if it's not. I'm having a difficult time doing the sync (openvas-feed-sync) as it returns connection refused and therefore doesnt download the scap and cert. The log:
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
[*] [2/3] Updating: Scap Data
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
[*] [3/3] Updating: Cert Data
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
I can bypass the nvt by using greenbone-nvt-sync --curl but the same method doesnt work for the cert and scap.
Is there a way to bypass this? (Using Kali linux btw)
Thanks in advance and sorry if it's the wrong place.

**Comment by jjnicola** [comment]
Hello @himuura
Sorry, the issue tracker is not a support forum. The question is proper for the openvas-discuss mailing list http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss.
Close issue here.
