### ISSUE TITLE
fresh new install and no scan can ran

### ISSUE THREAD

**Issue by montjoie** [greenbone/openvas-scanner#1489]
Hello

I have installed a fresh new install via the docker-compose community edition.
I waited some hours for that update of feed are done.

Now I create a simple scan task and I got:
openvas-gvmd-1                 | event target:MESSAGE:2023-09-13 07h18.38 UTC:946: Target tegra (95472946-d41d-4854-94e7-e630d6ed8027) has been created by admin
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h18.55 UTC:994: Status of task  (786376ac-f30c-4e45-a4b1-8575e4c197a5) has changed to New
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h18.55 UTC:994: Task egra (786376ac-f30c-4e45-a4b1-8575e4c197a5) has been created by admin
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h18.59 UTC:1012: Status of task egra (786376ac-f30c-4e45-a4b1-8575e4c197a5) has changed to Requested
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h18.59 UTC:1012: Task egra (786376ac-f30c-4e45-a4b1-8575e4c197a5) has been requested to start by admin
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:19:51,223: INFO: (ospd.command.command) Scan 020fc711-8ff4-48af-9a45-46d7a5c1dfff added to the queue in position 2.
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h19.51 UTC:1014: Status of task egra (786376ac-f30c-4e45-a4b1-8575e4c197a5) has changed to Queued
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:19:54,163: INFO: (ospd.ospd) Currently 1 queued scans.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:19:54,573: INFO: (ospd.ospd) Starting scan 020fc711-8ff4-48af-9a45-46d7a5c1dfff.
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h19.56 UTC:1014: Status of task egra (786376ac-f30c-4e45-a4b1-8575e4c197a5) has changed to Running
openvas-mqtt-broker-1          | 1694589661: New connection from 172.20.0.4:42704 on port 1883.
openvas-mqtt-broker-1          | 1694589662: New client connected from 172.20.0.4:42704 as a95c7b00-c620-4558-bbc8-e5340f53592e (p5, c1, k0).
openvas-mqtt-broker-1          | 1694589670: Client a95c7b00-c620-4558-bbc8-e5340f53592e closed its connection.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:11,884: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Host scan finished.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:11,888: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Host scan got interrupted. Progress: 0, Status: RUNNING
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:11,889: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan interrupted.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,184: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan process is dead and its progress is 0
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,187: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan interrupted.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,193: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan process is dead and its progress is 0
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,194: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan interrupted.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,309: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan process is dead and its progress is 0
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,311: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan interrupted.
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,358: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan process is dead and its progress is 0
openvas-ospd-openvas-1         | OSPD[9] 2023-09-13 07:21:12,359: INFO: (ospd.ospd) 020fc711-8ff4-48af-9a45-46d7a5c1dfff: Scan interrupted.
openvas-gvmd-1                 | event task:MESSAGE:2023-09-13 07h21.12 UTC:1014: Status of task egra (786376ac-f30c-4e45-a4b1-8575e4c197a5) has changed to Interrupted

I feared to have done something bad so I cleaned all docker stuff and restarted again from scratch, but the problem is still here.

**Comment by montjoie** [comment]
There are several openvas container, which one do you want ?  I greped openvas from docker compose logs to https://bpa.st/UZ7A

**Comment by jjnicola** [comment]
Hi @montjoie 
I updated my containers and ran some scans. It works as expected.
Regarding the logs, I have 

``` bash
export CID=$(docker ps |grep ospd-openvas | awk '{print $1;}')
docker exec -it $CID /bin/bash
```

Once in the ospd-openvas container
``` bash 
cat /var/log/gvm/openvas.log 
```
That is the log I would like to see. It will show why openvas is failing

**Comment by montjoie** [comment]
The issue was in the host, some missing kernel options, strange that I didnt see any fail in either docker or openvas logs.
Thanks for your help

**Comment by jjnicola** [comment]
Hi @montjoie !
thanks for telling us. Can you provide some more information about the kernel options? which are the missing options? Thanks a lot in advance!
