### ISSUE TITLE
Openvas 10 Scanner - OMP Slave Issue with Openvas 9 Manager

### ISSUE THREAD

**Issue by falegk** [greenbone/openvas-scanner#150]
Hi,

When using an Openvas Manager 7.03 with an omp slave Openvas 6.0+beta1 scanner I run into the following issue:
The task is initiated by the Opevas 7.03 Manager, and I see it start on the Openvas 6.0+beta1 scanner. The task runs all the way to the end and when the Openvas 6.0+beta1 scanner completes the scan (state Done), the Openvas 7.03 Manager shows an internal error for the task. The log file entry below shows up in the openvasmd.log file on the Openvas 7.03 Manager.

```
md manage:WARNING:2018-08-10 16h32.56 EDT:21351: NVT '1.3.6.1.4.1.25623.1.0.108449' not found. Result not created.
md manage:WARNING:2018-08-10 16h33.21 EDT:21351: manage_cleanup_process_error: Error exit, setting running task to Internal Error

```
Are the two versions not compatible, or is this a bug with moving the task results from the Openvas 6.0+beta1 scanner to the Openvas 7.03 manager?

Any guidance would be greatly appreciated.

Thanks

### GVM versions
**gsa:**  7.0.3

**gvm:**  7.0.3

**openvas-scanner:** **6.0+beta1**

**gvm-libs:** 9.0.2

### Environment
**Operating system:** Ubuntu 16.04 & 18.04

**Installation method / source:** source installation

### Logfiles
```
md manage:WARNING:2018-08-10 16h32.56 EDT:21351: NVT '1.3.6.1.4.1.25623.1.0.108449' not found. Result not created.
md manage:WARNING:2018-08-10 16h33.21 EDT:21351: manage_cleanup_process_error: Error exit, setting running task to Internal Error

```

**Comment by jjnicola** [comment]
Hello @falegk 
Sorry, the issue tracker is not a support forum. The question is proper for the openvas-discuss mailing list http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss.
Close issue here.
