### ISSUE TITLE
Build requires MQTTClient.h

### ISSUE THREAD

**Issue by inferrna** [greenbone/openvas-scanner#1524]
Build stage requires MQTTClient.h but cmake doesn't check it. On ubuntu have to install libpaho-mqtt-dev

**Comment by ObscenityIB** [comment]
Same problem just occured today on 3aa31988fca3a5c7c7ac1a4132ff57d7bfbf9259.

First error:

```
-- Checking for module 'libgvm_base>=22.4'
--   Package 'libgvm_base', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.31/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - libgvm_base>=22.4
```

Which was resolved by installing `libgvm-dev`.

Then the error mentioned in this issue:

```
[  1%] Building C object misc/CMakeFiles/openvas_misc_shared.dir/plugutils.c.o
In file included from /home/user/THM/artifacts/openvas/openvas-scanner/misc/plugutils.c:23:
/usr/include/gvm/util/mqtt.h:14:10: fatal error: MQTTClient.h: No such file or directory
```

Which was resolved by installing `libpaho-mqtt-dev` as mentioned on this issue.

**Comment by ArnoStiefvater** [comment]
Thanks for the clarification but we already have libpaho-mqtt-dev listed in our [INSTALL.md](https://github.com/greenbone/gvm-libs/blob/7ca7630b5542097dfabdedc2c3234232f70719c7/INSTALL.md?plain=1#L57) and [community documentation](https://greenbone.github.io/docs/latest/22.4/source-build/index.html#gvm-libs) as prerequisite.

**Comment by ObscenityIB** [comment]
I see, thanks for that, that seems to link to a different repository, this repository has instructions that differ.

https://github.com/greenbone/openvas-scanner/blob/main/INSTALL.md

**Comment by ArnoStiefvater** [comment]
Yes, because you first have to install gvm-libs before installing openvas-scanner. Gvm-libs and openvas-scanner have different prerequisites.
I also would rather have the gvm-libs parts we need in this repo for it to be easier to install but unfortunately this won't happen anytime soon.
