### ISSUE TITLE
Log4j Http active report False Positives

### ISSUE THREAD

**Issue by sed-ats** [greenbone/openvas-scanner#1531]
### Actual behavior

I updated the scanner from version 22.7.3 to version 22.7.9

and began to receive a huge number of false positive alerts

Apache Log4j 2.0.x Multiple Vulnerabilities (TCP, Log4Shell) - Active Check
Apache Log4j 2.0.x Multiple Vulnerabilities (UDP, Log4Shell) - Active Check
Apache Log4j 2.0.x Multiple Vulnerabilities (HTTP Web Root, Log4Shell) - Active Check

### GVM versions

**gsa:  22.08.0** 

**gvm: 23.1.0** 

**openvas: 22.7.9** 

**gvm-libs: 22.7.3**

**openvas-smb: 22.5.6**

**ospd-openvas:  22.6.2**

### Environment

**Operating system: Ubuntu 22.04.3 LTS**

**Installation method: source installation**

**Comment by jjnicola** [comment]
Hello @sed-ats 
Is this a Windows target?

**Comment by sed-ats** [comment]
> Hello @sed-ats Is this a Windows target?

I didn't see any pattern
for example, on Windows it sometimes detects
Apache Log4j 2.0.x Multiple Vulnerabilities (TCP, Log4Shell) -  on 49668/tcp, 49666/tcp, 49674/tcp, 445/tcp port

on MacOS and Linux(Ubuntu) it seems like it’s random

port 7000/tcp was opened on the MacBook and also
Apache Log4j 2.0.x Multiple Vulnerabilities (HTTP Web Root, Log4Shell)

on Linux on 80/tcp 67/udp 8200/tcp port
Apache Log4j 2.0.x Multiple Vulnerabilities (HTTP Web Root, Log4Shell)
Apache Log4j 2.0.x Multiple Vulnerabilities (TCP, Log4Shell)
Apache Log4j 2.0.x Multiple Vulnerabilities (UDP, Log4Shell)

**Comment by sed-ats** [comment]
Hello everyone, I'm closing the task because I found a problem and it was on the server side. 
the problem was incorrect limits in /etc/security/limits.conf

**Comment by jjnicola** [comment]
@sed-ats thanks a lot for notifying
Best regards
