### ISSUE TITLE
Cannot use space in username

### ISSUE THREAD

**Issue by TheGroundZero** [greenbone/openvas-scanner#159]
### Expected behavior

Successfully create a new credential with a space in the username.

### Current behavior

(Status code: 400) Operation 'Create Credential' failed
Given login was invalid

### Steps to reproduce
1. Create a new credential
2. Enter username with a space in it
3. Try to save credential

### GVM versions
**gsa:** (gsad --version)  
7.0.3

**gvm:** (gvmd --version)  
/

**openvas-scanner:** (openvassd --version)  
5.1.3

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**  
Greenbone Security Manager Community Edition

**Installation method / source:** (packages, source installation)  
ISO from site

### Logfiles

```

```

**Comment by jjnicola** [comment]
Hello @TheGroundZero,
spaces in credential in username are currently not allowed. Therefore, this is not a bug.
Regards,
Juan

**Comment by TheGroundZero** [comment]
While definitely not recommended, it is possible to create accounts with spaces in the username.

The current configuration of the scanner as such prevents a user from testing systems where a username contains a space (and it is not possible to create a seperate account for testing).

If not a bug, I would request you consider this to be at least a Feature Request.

**Comment by cfi-gb** [comment]
As a side-note the scanner is not responsible for this task. It could still worth to create a new issue at https://github.com/greenbone/gvm/issues to make the error message at least include that an unsupported char is used.
