### ISSUE TITLE
Collation version issue

### ISSUE THREAD

**Issue by Viswayasas** [greenbone/openvas-scanner#1659]
I've tried to install in kali 2024.1. Did apt update, upgrade and dist-upgrade. During the gvm-setup it shows collation version issue. Had to run these commands in order to successfully complete gvm-setup:

sudo -u postgres psql -c 'ALTER DATABASE template1 REFRESH COLLATION VERSION;'

sudo -u postgres psql -c 'ALTER DATABASE postgres REFRESH COLLATION VERSION;'

Post running this the collation issue was resolved and could use the application.

**Comment by cfi-gb** [comment]
This is not an issue / bug in the Greenbone software stack but something PostgreSQL specific (`gvm-setup` is also not maintained by Greenbone).

Please contact the Kali packaging team over at https://bugs.kali.org if you think there should be done something in e.g. `gvm-setup`.
