### ISSUE TITLE
Erro scan interrupted

### ISSUE THREAD

**Issue by mateusfilipeferraz** [greenbone/openvas-scanner#1755]
Eu vinha há dias enfrentando o problema de que a varredura era interrompida em 0%, ou seja, nem iniciava. Minha instalação era nova, feita em uma VM com 8 GB de RAM e 4 vCPUs. Tentei aumentar a memória RAM, mas não adiantou. A única solução foi pesquisar até chegar ao comando `sudo setcap cap_net_raw+ep $(which openvas) que basicamente reduz a exigência de privilégios para o ping, já que é assim que o OpenVAS detecta se o host está online.

**Comment by nichtsfrei** [comment]
Hello,

Please communicate in English.

Yes, we are aware that OpenVAS requires higher privileges when neither `sudo` nor `doas` is used. This is reflected in our Docker image (see: https://github.com/greenbone/openvas-scanner/blob/main/.docker/prod.Dockerfile#L57C1-L57C65). That said, when installing from source code directly, `sudo` is recommended in the installation documentation (see: https://greenbone.github.io/docs/latest/22.4/source-build/index.html#setting-up-sudo-for-scanning).

**Comment by jjnicola** [comment]
As this is not an issue / bug in the scanner it could be better to use https://forum.greenbone.net/ for support/questions.
