### ISSUE TITLE
How do I disable scanning of connected hostnames?

### ISSUE THREAD

**Issue by asmaack** [greenbone/openvas-scanner#177]
### Expected behavior
An openvas scan of a single domain should produce results for that domain only. 

### Current behavior
Any connected domain/hostname to my target domain is scanned and reported.

### Steps to reproduce
1. Created a task with Advanced task Wizard, selecting Full and fast policy

I'm having a hard time in preventing my scanner from following and scanning other, connected, hostnames.

For example, let's say I want to execute a scan of target www.domx.de, which is an alias of www.domx.net, which is on IP address 1.2.3.4. The webserver will serve a certificate from it's IP address with secondary domain names www.cust1.com, www.cust2.com. 

As it is, the openvas scanner attacks ALL these domains, and not just the single one I want, which is "www.domx.de". This behaviour results in my audits scanning too much, taking too long, attacking other customer's web sites, and the reports/results can be huge.

I have been experimenting with the server config (openvassd.conf) and scan config nvt settings to try to find a way to disable this behaviour, but to no avail!

Am I missing out on something obvious here? Is there a single setting in the config file to disable this, or a single nvt?

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 8.0+beta2
GIT revision f51173b63-master

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta1
GIT revision 70463a9d-master

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0+beta2
GIT revision fcc9de6-master

**gvm-libs:**
commit 3cb8af8fb8db54ec076b4d7212a0e99628c8b645 (HEAD -> master, origin/master, origin/HEAD)

**openvas-smb:**
--- not installed ---

### Environment
**Operating system:**
$ uname -a
Linux xxx 4.15.0-34-generic #37-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source:** 
(source installation)

**Comment by cfi-gb** [comment]
@asmaack Note the following in the used template:

> 3. be aware that this is not a support forum. If your issue is more a question
   than a bug report, please use https://community.greenbone.net/c/gse instead.

**NOTE:** This is generally valid for nearly every project using the github issue trackers. Only use those for bug reports and mailing lists / forums for support questions.

Please close here and use the mentioned community portal for your question. Thanks for your help to keep the communication channels clean and consistent.

**Comment by cfi-gb** [comment]
Just to note that the discussion around this topic has been moved to https://community.greenbone.net/t/how-do-i-disable-scanning-of-connected-hostnames/341
