### ISSUE TITLE
Possible unused "use_mac_addr" scanner preference

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/openvas-scanner#179]
https://github.com/greenbone/openvas-scanner/commit/8b7240d8c35c6cafe8d84d60feb4b11eac6413f0#diff-f27e194bfd44f2d386e09b3e08a2cc3bL1037 seems to have removed the usage of the "use_mac_addr" scanner preference but the preference is still included / defined here:

https://github.com/greenbone/openvas-scanner/blob/v6.0%2Bbeta1/doc/openvassd.8.in#L112-L113

https://github.com/greenbone/openvas-scanner/blob/v6.0%2Bbeta1/src/openvassd.c#L137

which could be removed as well.

**Comment by kroosec** [comment]
Removed in https://github.com/greenbone/openvas-scanner/pull/181
