### ISSUE TITLE
openvassd silently exits if it can't connect to the Redis socket

### ISSUE THREAD

**Issue by richstokes** [greenbone/openvas-scanner#195]
No error printed, even with -f flag set. OpenVAS Scanner 6.0+Beta1

**Comment by kroosec** [comment]
Hey @richstokes, thanks for the report. You can find the error messages in the logs file:

==> /usr/var/log/gvm/openvassd.log <==
<pre>lib  kb:CRITICAL:2018-11-11 16h32.42 utc:32275: get_redis_ctx: redis connection error: No such file or directory
lib  kb:CRITICAL:2018-11-11 16h32.42 utc:32275: redis_new: cannot access redis at &apos;/tmp/redis.sock&apos;
lib  kb:CRITICAL:2018-11-11 16h32.42 utc:32275: get_redis_ctx: redis connection error: No such file or directory
</pre>
