### ISSUE TITLE
Review GnuTLS priority string / keywords of scanner

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/openvas-scanner#206]
While doing https://github.com/greenbone/openvas-scanner/pull/205 i've noticed a few things:

1. The priority string of set_gnutls_protocol:

    https://github.com/greenbone/openvas-scanner/blob/v6.0%2Bbeta1/misc/network.c#L452-L465

    is using a different one then open_stream_connection/open_stream_connection_ext:

    https://github.com/greenbone/openvas-scanner/blob/v6.0%2Bbeta1/misc/network.c#L1079

2. We might to evaluate additional keywords for the current priority string of the scanner so it can connect to as many services as possible, even if broken / having outdated ciphers or similar:

    https://gnutls.org/manual/html_node/Priority-Strings.html

    e.g. ``%SERVER_PRECEDENCE`` could be really useful:

    > The ciphersuite will be selected according to server priorities and not the client’s.

**Comment by kroosec** [comment]
1. Different one, due to the explicit choice of TLS version in that function. We still may want to use %COMPAT here too.

2. Have gone quickly through the list, and haven't found anything that we ought to add.

`e.g. %SERVER_PRECEDENCE could be really useful:`

Has no effect in the case of a client.

> %SERVER_PRECEDENCE: (Server side only) Pick the first ciphersuite from the server list supported by the client (default: pick the first from the client list supported by the server)

**Comment by cfi-gb** [comment]
> 1. ... We still may want to use %COMPAT here too.

https://github.com/greenbone/openvas-scanner/pull/207
