### ISSUE TITLE
Cannot start openvassd

### ISSUE THREAD

**Issue by jhclifton** [greenbone/openvas-scanner#217]
i have installed OopenVAS v9 on Oracle EL, and am getting a "503: failed to start task, service temporarily down" 
I noticed openvassd isn't running, upon trying to start i, I get:
 openvassd start

(openvassd:21530): lib  kb_redis-CRITICAL **: get_redis_ctx: redis connection error: No such file or directory

(openvassd:21530): lib  kb_redis-CRITICAL **: redis_new: cannot access redis at '/var/run/redis/redis.sock'

(openvassd:21530): lib  kb_redis-CRITICAL **: get_redis_ctx: redis connection error: No such file or directory

However redis is running when i do a "ps -ef |grep redis"

Any help would be appreciated.
--joe

**Comment by cfi-gb** [comment]
Hi,

please note the following in the presented template when creating a new issue:

> 3. be aware that this is not a support forum. If your issue is more a question
   than a bug report, please use https://community.greenbone.net/c/gse instead.

As this is clearly no bug and just a setup / environment issue i'm closing this issue as invalid.
