### ISSUE TITLE
openvas-scanner-6.0-beta2 don't compile

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#218]
### Expected behavior
Working compiler run
### Current behavior
the build fails

### GVM versions

**gvm-libs:**
gvm-libs 1 beta2

### Environment
**Operating system:**
CentOS 7.6
 
Build error:
In file included from /usr/include/arpa/inet.h:22:0,
                 from /builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:34:
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'extractack':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:429:23: error: 'struct tcphdr' has no member named 'th_ack'
  ret = htonl(ntohl(tcp->th_ack) - 1);
                       ^
In file included from /usr/include/bits/byteswap.h:35:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/bits/waitstatus.h:64,
                 from /usr/include/stdlib.h:42,
                 from /builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:33:
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'extractsport':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:446:18: error: 'struct tcphdr' has no member named 'th_sport'
  return ntohs(tcp->th_sport);
                  ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'issynack':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:462:13: error: 'struct tcphdr' has no member named 'th_flags'
   return tcp->th_flags == (TH_SYN | TH_ACK);
             ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:462:28: error: 'TH_SYN' undeclared (first use in this function)
   return tcp->th_flags == (TH_SYN | TH_ACK);
                            ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:462:28: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:462:37: error: 'TH_ACK' undeclared (first use in this function)
   return tcp->th_flags == (TH_SYN | TH_ACK);
                                     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'mktcp':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:490:5: error: 'struct tcphdr' has no member named 'th_sport'
  tcp->th_sport = htons(sport);
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:491:5: error: 'struct tcphdr' has no member named 'th_dport'
  tcp->th_dport = htons(dport);
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:492:5: error: 'struct tcphdr' has no member named 'th_seq'
  tcp->th_seq = th_ack;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:493:5: error: 'struct tcphdr' has no member named 'th_ack'
  tcp->th_ack = 0;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:494:5: error: 'struct tcphdr' has no member named 'th_x2'
  tcp->th_x2 = 0;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:495:5: error: 'struct tcphdr' has no member named 'th_off'
  tcp->th_off = 5;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:496:5: error: 'struct tcphdr' has no member named 'th_flags'
  tcp->th_flags = flag;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:497:5: error: 'struct tcphdr' has no member named 'th_win'
  tcp->th_win = 4096;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:498:5: error: 'struct tcphdr' has no member named 'th_sum'
  tcp->th_sum = 0;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:499:5: error: 'struct tcphdr' has no member named 'th_urp'
  tcp->th_urp = 0;
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:508:5: error: 'struct tcphdr' has no member named 'th_sum'
  tcp->th_sum = in_cksum((unsigned short *) tcpsumdata, 12 + sizeof (struct tcphdr));
     ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'mktcpv6':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:521:6: error: 'struct tcphdr' has no member named 'th_sport'
   tcp->th_sport = htons(sport);
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:522:6: error: 'struct tcphdr' has no member named 'th_dport'
   tcp->th_dport = htons(dport);
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:523:6: error: 'struct tcphdr' has no member named 'th_ack'
   tcp->th_ack = htonl (rand ());
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:524:6: error: 'struct tcphdr' has no member named 'th_seq'
   tcp->th_seq = th_ack;
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:525:6: error: 'struct tcphdr' has no member named 'th_off'
   tcp->th_off = 5;
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:526:6: error: 'struct tcphdr' has no member named 'th_flags'
   tcp->th_flags = flag;
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:527:6: error: 'struct tcphdr' has no member named 'th_win'
   tcp->th_win = htons (5760);
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:528:6: error: 'struct tcphdr' has no member named 'th_urp'
   tcp->th_urp = 0;
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:529:6: error: 'struct tcphdr' has no member named 'th_sum'
   tcp->th_sum = 2;
      ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'sendpacket':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:545:60: error: 'TH_SYN' undeclared (first use in this function)
  char           *pkt = mktcp (src, magic, dst, dport, ack, TH_SYN);
                                                            ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:592:51: error: 'TH_RST' undeclared (first use in this function)
      rst = mktcp(src, magic, dst, sport, ack + 1, TH_RST);
                                                   ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'v6_sendpacket':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:623:43: error: 'TH_SYN' undeclared (first use in this function)
   char *pkt = mktcpv6 (magic, dport, ack, TH_SYN);
                                           ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:667:47: error: 'TH_RST' undeclared (first use in this function)
         rst = mktcpv6 (magic, sport, ack + 1, TH_RST);
                                               ^
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c: In function 'issynack':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/nasl/nasl_builtin_synscan.c:463:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^

**Comment by tuxmaster5000** [comment]
It looks like, __FAVOR_BSD  was not defined.

**Comment by kroosec** [comment]
Thanks for the PR. Merged.
