### ISSUE TITLE
[openvas-scanner-6.0-beta2] error about uninitialized variable

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#223]
The build fails with:
/builddir/build/BUILD/openvas-scanner-6.0-beta2/src/openvassd.c: In function 'scanner_thread':
/builddir/build/BUILD/openvas-scanner-6.0-beta2/src/openvassd.c:500:13: error: 'soc' may be used uninitialized in this function [-Werror=maybe-uninitialized]
       close (soc);

**Comment by tuxmaster5000** [comment]
soc is not an problem, because it is protected by the if condition above.
So it is an misunderstood of the compiler.

**Comment by kroosec** [comment]
Thanks for the PR. Merged.
