### ISSUE TITLE
openvas-scanner-5.1.3 segfault with gb_ssl_weak_hash_algo.nasl

### ISSUE THREAD

**Issue by madmac2501** [greenbone/openvas-scanner#225]
Hi,

I’m getting this segfault when scanning. I’m using openvas scanner 5.1.3 from source.

SIGSEGV occured !
openvassd: testing 127.0.0.1 (/var/lib/openvas/plugins/2016/gb_ssl_weak_hash_algo.nasl)(sighand_segv+0x7d)[0x40d5bd]
/lib/x86_64-linux-gnu/libc.so.6(+0x350e0)[0x7fb7d17b80e0]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_cert_query+0x9e4)[0x7fb7d262abd4]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_func_call+0x327)[0x7fb7d262db67]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_exec+0x815)[0x7fb7d2618d05]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_exec+0x4ae)[0x7fb7d261899e]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_exec+0xecc)[0x7fb7d26193bc]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_exec+0xf44)[0x7fb7d2619434]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_exec+0xf44)[0x7fb7d2619434]
/usr/lib/x86_64-linux-gnu/libopenvas_nasl.so.9(nasl_exec+0xf44)[0x7fb7d2619434]

Best regards

**Comment by jjnicola** [comment]
Hi @madmac2501, could you provide more info? (e.g. service available in the system you are scanning).
Regards,
Juan

**Comment by madmac2501** [comment]
Hi @jjnicola I scanned an USM Appliance all in one machine. Both the scanner and the target were in the same machine, as you can see the target that I used was 127.0.0.1

Best regards
