### ISSUE TITLE
Compiling openvas-scanner branch openvas-scanner-5.1: error cast between incompatible pointer types

### ISSUE THREAD

**Issue by tps800** [greenbone/openvas-scanner#233]
### Expected behavior
Just warn or cast in a way not producing warnings or errors.

### Current behavior
Compiler breaks, because _-Werror=cast-function-type_ is set.

### Steps to reproduce
1. Download or checkout sources
2. Solve dependencies
3. Compile

### Environment
**Operating system:** Debian buster/sid

**Installation method / source:** source installation

```
HEAD is now at b9310b2 Merge pull request #212 from jjnicola/fix-no-nvt-category
Already up to date.
Already on 'openvas-scanner-5.1'
Your branch is up to date with 'origin/openvas-scanner-5.1'.
```

It is fixed in 'master', but not backported to 'openvas-scanner-5.1'.

**Comment by RockyYu** [comment]
I have an error when I installed scanner-5.1,and this is a bit like it .I don't konw how to solve it ,the error is as follow 👍

attack.c:1093:29: error: cast between incompatible function types from ‘void (*)(struct attack_start_args *)’ to ‘int (*)(void *)’ [-Werror=cast-function-type]
       pid = create_process ((process_func_t) attack_start, &args);

**Comment by kroosec** [comment]
Fixed in https://github.com/greenbone/openvas-scanner/pull/237
