### ISSUE TITLE
 error: cast between incompatible function types from ‘void (*)(struct attack_start_args *)’ to ‘int (*)(void *)’ [-Werror=cast-function-type]        pid = create_process ((process_func_t) attack_start, &args);

### ISSUE THREAD

**Issue by RockyYu** [greenbone/openvas-scanner#235]
### Current behavior
/usr/src/openvas9/openvas-scanner-5.1.3/src/attack.c: In function ‘attack_network’:
/usr/src/openvas9/openvas-scanner-5.1.3/src/attack.c:1085:29: error: cast between incompatible function types from ‘void (*)(struct attack_start_args *)’ to ‘int (*)(void *)’ [-Werror=cast-function-type]
       pid = create_process ((process_func_t) attack_start, &args);
                             ^
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/openvassd.dir/build.make:63：src/CMakeFiles/openvassd.dir/attack.c.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:128：src/CMakeFiles/openvassd.dir/all] 错误 2
make: *** [Makefile:163：all] 错误 2

### Steps to reproduce
1.cd build
2.cmake ..
3.make

### GVM versions

openvas-scanner:5.1.3

gvm-libs:9.0.3

### Environment
Operating system:kali-linux-2018.4-amd64.iso

-- Configuring the Scanner...
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at CMakeLists.txt:33 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Install prefix: /usr/local
-- Checking for module 'libopenvas_nasl>=9.0.3'
--   Found libopenvas_nasl, version 9.0.3
-- Checking for module 'libopenvas_base>=9.0.3'
--   Found libopenvas_base, version 9.0.3
-- Checking for module 'libopenvas_misc>=9.0.3'
--   Found libopenvas_misc, version 9.0.3
-- Checking for module 'glib-2.0>=2.32'
--   Found glib-2.0, version 2.58.1
-- Looking for libgcrypt...
-- Looking for libgcrypt... /usr/lib/x86_64-linux-gnu/libgcrypt.so
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/openvas9/openvas-scanner-5.1.3/build

**Installation method / source: source installation

**Comment by cfi-gb** [comment]
Hi,

please use the search function or check the existing open issues before posting a new issue. There is already one available about this in https://github.com/greenbone/openvas-scanner/issues/233.
