### ISSUE TITLE
openvas use masscan only , thats had no data found 

### ISSUE THREAD

**Issue by cgjue** [greenbone/openvas-scanner#238]
Expected behavior
masscan could be used and the found data could be inserted into database

Current behavior
masscan could be used but the found data could not be inserted into database
i use openvas-nasl to debug the gb_masscan.nasl ,found that the gb_masscan.nasl could be called and the masscan found data, and "scanner_add_port(proto:proto, port:port);" in gb_masscan.nasl called。So I think the data flow went to gvmd。
why the data found could not be inserted into database? I opened the database log =ALL, that made me can see all sql data.
complared with use host discovery ，I found many inserted sql data in database log，but use masscan coul not found
you can make a simple test
Steps to reproduce
scan config -->choose port scanner--> choose masscan only
choose target one ip
creat one target
GVM versions
gsa: (gsad --version)
Greenbone Security Assistant 8.0+beta3
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gvm: (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta2
Manager DB revision 200
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

openvas-scanner: (openvassd --version)
OpenVAS Scanner 6.0+beta3
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison deraison@nessus.org
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gvm-libs:

openvas-smb:

Environment
Operating system: 
debian 8

Installation method / source: (packages, source installation)
use the source from github and make it .

**Comment by cfi-gb** [comment]
As advised in https://github.com/greenbone/gvmd/issues/318 please use https://community.greenbone.net/c/gse for your questions.

**Comment by cgjue** [comment]
thank you all the same
