### ISSUE TITLE
running at 1% forever 

### ISSUE THREAD

**Issue by Zormgard** [greenbone/openvas-scanner#247]
Hi there
I have installed, updated and synced openVAS on a Ubuntu system. I create a new target & task, and then start the scan. I have placed the refresher at 30-sec. The process starts running, but it will stay at 1% for ever.? 

What is coursing this?

**Comment by cfi-gb** [comment]
Hi,

and thanks for your report. Please note the following in the issue template which gets presented when creating a new issue:

> 3. be aware that this is not a support forum. If your issue is more a question
   than a bug report, please use https://community.greenbone.net/c/gse instead.

As this is very unlikely a bug in the scanner and more an environmental issue (e.g. using "All UDP" or similar portlists are known to take ages) i'm closing this here. Please ask your question in the related community portal.

**Comment by bjoernricks** [comment]
And please take a look at https://community.greenbone.net/search?q=1%20percent for a lot of discussions and help for this issue
