### ISSUE TITLE
nasl_http.c:182:19 type mismatch

### ISSUE THREAD

**Issue by Eveink** [greenbone/openvas-scanner#255]
`nasl_http.c:182:19: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t’ [-Werror=format=]`

shoud cast strlen (data) with (long)strlen (data)

*Edit* Removed the cross-compiling question which is unrelated to the initial report.

**Comment by kroosec** [comment]
Thanks for the report. This was fixed in https://github.com/greenbone/openvas-scanner/pull/299
