### ISSUE TITLE
openvas_scanner_connect_unix: Failed to connect to scanner: Connection refused

### ISSUE THREAD

**Issue by pyron83** [greenbone/openvas-scanner#270]
### Expected behavior

openvassd should run with the unix-socket specified in "/usr/local/etc/openvas/openvassd.conf" 
(in my case the content is: "kb_location = /var/run/redis/redis-server.sock")

### Current behavior
openvassd ignores the "kb_location" directive.
This is a recent issue from the last updates from Github.

### Steps to reproduce
try to start the openvassd with the last version from git (in my case OpenVAS Scanner 6.0+beta3
GIT revision ed07eca-master)

### GVM versions
**openvas-scanner:**
OpenVAS Scanner 6.0+beta3
GIT revision ed07eca-master

**gvm-libs:**
1.0+beta3~git-7fecb224-master

**gvmd**
Greenbone Vulnerability Manager 8.0+beta2
GIT revision f0918e0f-master
Manager DB revision 205

**gsad**
Greenbone Security Assistant 8.0+beta3
GIT revision fdf537f2c-master

### Environment
**Operating system:**
debian 9.6

**Installation method / source:** (packages, source installation)
source git installation

### Logfiles
md   main:WARNING:2019-02-06 11h04.43 utc:11981: openvas_scanner_connect_unix: Failed to connect to scanner (/usr/local/var/run/openvassd.sock): Connection refused
```

```

**Comment by kroosec** [comment]
Hey @pyron83,

From the CHANGES file:
* Setting 'kb_location' has been renamed to 'db_address'.

For further questoins, please use http://community.greenbone.net/

**Comment by pyron83** [comment]
I'm sorry I missed that.

Thanks.

**Comment by pyron83** [comment]
> Hey @pyron83,
> 
> From the CHANGES file:
> 
>     * Setting 'kb_location' has been renamed to 'db_address'.
> 
> 
> For further questoins, please use http://community.greenbone.net/

the same problem happens with 'db_address'
