### ISSUE TITLE
Can't update the feeds

### ISSUE THREAD

**Issue by Noname2244** [greenbone/openvas-scanner#37]
It's not possible to update the feeds

It's not possible to update

prompt :~$ sudo greenbone-scapdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

prompt :~$ sudo greenbone-certdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

**Comment by kroosec** [comment]
Hi @Noname2244,

Thanks for the report. Do you still face this issue ? Does it happen with greenbone-nvt-sync too ?

**Comment by Noname2244** [comment]
yes the issue still persists and with greenbone-nvt-sync too.
`root@9d347a932612:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]`

There is no ping utility or trace, but SSH (there is no other util availble in the image) so I sshed to port 80 , in a attempt to see if there is any connectivity at all, and there is:

`root@9d347a932612:/# ssh -p 80 89.146.224.58
ssh_exchange_identification: Connection closed by remote host`

89.146.224.58 closes the connection as expected.

**Comment by janowagner** [comment]
Likely the maximum number of concurrent syncs was reached.
The server additionally restricts the concurrent connection from the same IP.
Please try at a different (day)time or from another IP (be aware of NAT).

This problem is not related to the OpenVAS Scanner or the sync script as such.
So I am closing this issue at this point.
