### ISSUE TITLE
Configuration And Setup

### ISSUE THREAD

**Issue by LogoiLab** [greenbone/openvas-scanner#41]
There is no solid documentation for configuration and setup. I install the software from my system repositories, everything works untill I go to rebuild the database at which point it complains about not being able to reach /var/run/openvassd.sock the file exists the service is running and the process is sudoed what gives? So maybe it's just my system packages. I go download the source. Try to follow install documentation provided in the download. Compiling with make fails because the creators have set flags for GCC to FAIL ON WARNING. Your project provides a horrible user experience and next to zero documentation. I get that it is a large project. Documentation sucks but it must be done. The maintainers should assume that people are going to want to run your software on systems other than Kali Linux.

**Comment by janowagner** [comment]
The first paragraph of the INSTALL file  (OpenVAS-9) says:

"""
Please note: The reference system used by most of the developers is Debian
GNU/Linux 'Jessie' 8. The build might fail on any other systems.
Also it is necessary to install dependent development packages.
"""

3rd parties managed to build it on a variety of other systems, like it was done for Kali.
Sometimes we receive helpful patches from these parties and we appreciate this to make
it easier for others to build.

We will improve the general documentation as time and resources permit.
However, this is not subject to a single issue, so I am closing this one and leave it
up to our continuous activity.
