### ISSUE TITLE
[7.0.0] coredump loading the plug-ins

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#418]
In the log I see this:

> sd   main:MESSAGE:2019-11-01 09h07.47 utc:5106: openvas 7.0.0 started
> lib  kb:  DEBUG:2019-11-01 09h07.47 utc:5106: fetch_max_db_index: maximum DB number: 16
> util gpgme:MESSAGE:2019-11-01 09h07.47 utc:5107: Setting GnuPG dir to '/var/lib/greenbone/openvas/gnupg'
> util gpgme:MESSAGE:2019-11-01 09h07.47 utc:5107: Using OpenPGP engine version '2.0.22'
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: SIGSEGV occurred!
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: openvas: Reloaded 100 of 53156 NVTs (0% / ETA: 00:00)(sighand_segv+0x3b) [0x55d9ab6e940b]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: /lib64/libc.so.6(+0x363b0) [0x7f62c48063b0]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: /lib64/libopenvas_nasl.so.11(nasl_verify_signature+0x297) [0x7f62c7409137]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: /lib64/libopenvas_nasl.so.11(init_nasl_ctx+0x482) [0x7f62c73fa6d2]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: /lib64/libopenvas_nasl.so.11(exec_nasl_script+0x103) [0x7f62c73e4813]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: openvas: Reloaded 100 of 53156 NVTs (0% / ETA: 00:00)(nasl_plugin_add+0xe2) [0x55d9ab6e5bc2]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: openvas: Reloaded 100 of 53156 NVTs (0% / ETA: 00:00)(+0x96bb) [0x55d9ab6e76bb]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: openvas: Reloaded 100 of 53156 NVTs (0% / ETA: 00:00)(create_process+0xe4) [0x55d9ab6e91c4]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: openvas: Reloaded 100 of 53156 NVTs (0% / ETA: 00:00)(plugins_init+0xe7) [0x55d9ab6e7b87]
> sd   main:WARNING:2019-11-01 09h07.47 utc:5107: openvas: Reloaded 100 of 53156 NVTs (0% / ETA: 00:00)(start_single_task_scan+0x48) [0x55d9ab6e6508]
> 
Back trace:
{   "signal": 11
,   "executable": "/usr/sbin/openvas"
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 140062226420023
                ,   "build_id": "bbd3c26f3aa864e95ed6044b584153c94ed02048"
                ,   "build_id_offset": 287031
                ,   "function_name": "nasl_verify_signature"
                ,   "file_name": "/lib64/libopenvas_nasl.so.11"
                }
              , {   "address": 140062226360018
                ,   "build_id": "bbd3c26f3aa864e95ed6044b584153c94ed02048"
                ,   "build_id_offset": 227026
                ,   "function_name": "init_nasl_ctx"
                ,   "file_name": "/lib64/libopenvas_nasl.so.11"
                }
              , {   "address": 140062226270227
                ,   "build_id": "bbd3c26f3aa864e95ed6044b584153c94ed02048"
                ,   "build_id_offset": 137235
                ,   "function_name": "exec_nasl_script"
                ,   "file_name": "/lib64/libopenvas_nasl.so.11"
                }
              , {   "address": 94393372400578
                ,   "build_id": "7c2182a9c5aa9875254bcbe5d17f83a0edfa3c4d"
                ,   "build_id_offset": 31682
                ,   "function_name": "nasl_plugin_add"
                ,   "file_name": "/usr/sbin/openvas"
                }
              , {   "address": 94393372407483
                ,   "build_id": "7c2182a9c5aa9875254bcbe5d17f83a0edfa3c4d"
                ,   "build_id_offset": 38587
                ,   "function_name": "plugins_reload_from_dir"
                ,   "file_name": "/usr/sbin/openvas"
                }
              , {   "address": 94393372414404
                ,   "build_id": "7c2182a9c5aa9875254bcbe5d17f83a0edfa3c4d"
                ,   "build_id_offset": 45508
                ,   "function_name": "create_process"
                ,   "file_name": "/usr/sbin/openvas"
                }
              , {   "address": 94393372408711
                ,   "build_id": "7c2182a9c5aa9875254bcbe5d17f83a0edfa3c4d"
                ,   "build_id_offset": 39815
                ,   "function_name": "plugins_init"
                ,   "file_name": "/usr/sbin/openvas"
                }
              , {   "address": 94393372402952
                ,   "build_id": "7c2182a9c5aa9875254bcbe5d17f83a0edfa3c4d"
                ,   "build_id_offset": 34056
                ,   "function_name": "start_single_task_scan"
                ,   "file_name": "/usr/sbin/openvas"
                }
              , {   "address": 94393372404084
                ,   "build_id": "7c2182a9c5aa9875254bcbe5d17f83a0edfa3c4d"
                ,   "build_id_offset": 35188
                ,   "function_name": "openvas"
                ,   "file_name": "/usr/sbin/openvas"
                } ]
        } ]
}

**Comment by ArnoStiefvater** [comment]
This issue is very old. If this issue still exists please reopen and supply updated info.
