### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [greenbone/openvas-scanner#446]
I would like to point out that an identifier like “[`_OPENVAS_H`](https://github.com/greenbone/openvas/blob/d12adfde604fbfcb5cafacd31cb7a1d79069f857/src/openvas.h#L25 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by bjoernricks** [comment]
Feel free to provide a pull request.
