### ISSUE TITLE
error: passing argument 1 of ‘pcap_findalldevs’ from incompatible pointer type [-Werror=incompatible-pointer-types]

### ISSUE THREAD

**Issue by sarulon** [greenbone/openvas-scanner#511]
cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

after cmake ..
when i run make i get this error:

Scanning dependencies of target openvas_misc_shared
[  1%] Building C object misc/CMakeFiles/openvas_misc_shared.dir/bpf_share.c.o
/tmp/gvm10/openvas-6.0.1/misc/bpf_share.c: In function ‘bpf_open_live’:
/tmp/gvm10/openvas-6.0.1/misc/bpf_share.c:70:31: error: passing argument 1 of ‘pcap_findalldevs’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   70 |     iface = pcap_findalldevs (errbuf);
      |                               ^~~~~~
      |                               |
      |                               char *
In file included from /usr/include/pcap.h:43,
                 from /tmp/gvm10/openvas-6.0.1/misc/bpf_share.c:27:
/usr/include/pcap/pcap.h:519:31: note: expected ‘pcap_if_t **’ {aka ‘struct pcap_if **’} but argument is of type ‘char *’
  519 | PCAP_API int pcap_findalldevs(pcap_if_t **, char *);
      |                               ^~~~~~~~~~~~
/tmp/gvm10/openvas-6.0.1/misc/bpf_share.c:70:13: error: too few arguments to function ‘pcap_findalldevs’
   70 |     iface = pcap_findalldevs (errbuf);
      |             ^~~~~~~~~~~~~~~~
In file included from /usr/include/pcap.h:43,
                 from /tmp/gvm10/openvas-6.0.1/misc/bpf_share.c:27:
/usr/include/pcap/pcap.h:519:14: note: declared here
  519 | PCAP_API int pcap_findalldevs(pcap_if_t **, char *);
      |              ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [misc/CMakeFiles/openvas_misc_shared.dir/build.make:63: misc/CMakeFiles/openvas_misc_shared.dir/bpf_share.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:168: misc/CMakeFiles/openvas_misc_shared.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by ArnoStiefvater** [comment]
In the error message it is written that the following is done:
`iface = pcap_findalldevs (errbuf);`

But thats nonsense. In old versions of openvas we do `iface = pcap_lookupdev (errbuf);` and in new versions we do `(pcap_findalldevs (&alldevsp, errbuf)` but never `iface = pcap_findalldevs (errbuf);`. 

I have tried to compile the openvas version you are using and there are no issues. Maybe something is wrong in your build environment. You could try to clean it and build again.

**Comment by sarulon** [comment]
Hello,
You probably right.
I will clean and try again

**Comment by JRWR** [comment]
To update, I'm getting this on Kali Rolling right now, this is most likely due to openvas-7.0.1 as the current GVM11 release tar.gz and libpcap-1.9.1

Looking at the source code of openvas7.0.1 it does have `iface = pcap_lookupdev (errbuf);` being used.

This release is linked here: https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674

**Comment by cfi-gb** [comment]
> Looking at the source code of openvas7.0.1 it does have `iface = pcap_lookupdev (errbuf);` being used.

Which is correct. The initial report has shown the following:

```
70 | iface = pcap_findalldevs (errbuf);
```

which is something different then `iface = pcap_lookupdev (errbuf); ` and which doesn't exist for the 6.0.1 or any previous / later release:

https://github.com/greenbone/openvas/blob/v6.0.1/misc/bpf_share.c#L70
https://github.com/greenbone/openvas/blob/v7.0.1/misc/bpf_share.c#L70
https://github.com/greenbone/openvas/blob/49fbd622336ea1f93b0e025a0dcc0a94bca9e549/misc/bpf_share.c#L74

**Comment by JRWR** [comment]
Right, Overall the quickest fix is  just to compile and install libpcap 1.8.0 for openvas 7.0.1 (Current Stable)
