### ISSUE TITLE
gvm 11 new scan task severity error

### ISSUE THREAD

**Issue by muratdogan1** [greenbone/openvas-scanner#600]
Hi 

I am getting gvm 11 scan task error

what should I do

log file 
2020-09-17 11:42:53,085 OSPD - openvas: WARNING: (ospd_openvas.daemon) Error creating feed lock file. Trying again later...
2020-09-17 14:03:49,613 OSPD - openvas: ERROR: (ospd_openvas.daemon) OpenVAS Scanner failed to load NVTs. Command '['openvas', '--update-vt-info']' died with <Signals.SIGABRT: 6>.
![gvm11](https://user-images.githubusercontent.com/7044364/93585588-b2a56c00-f9af-11ea-9cde-19e45b68e396.jpg)

**Comment by robsd** [comment]
I have this issue also

![image](https://user-images.githubusercontent.com/8268467/98704525-a963ca80-2374-11eb-9e68-c37d44dbc18d.png)

**Comment by robsd** [comment]
Needed this for my assignment 🙄  thanks Greenbone for renaming and destroying the ability to get your stupid application working, nice one guys

**Comment by cfi-gb** [comment]
@robsd I have deleted your previous comment. A bugtracker is not the place for rants like this, no one is e.g. breaking things on purpose.

Please try to focus on the actual problem. If you are not getting the exact `died with <Signals.SIGABRT: 6>` message in your logs (you only have posted a screenshot) and the Error in the "Error messages" tab says something about "Failed to connect to scanner" then this is very likely just a setup problem. If this is the case you can find a lot of information on this message and various solution suggestions here:

https://community.greenbone.net/t/severity-error-could-not-connect-to-server/5192

**Comment by jjnicola** [comment]
Hi!
This seems not to be a bug, but a configuration problem. If you consider that this is a bug, please provide more information, the one required in the issue template.

**Comment by robsd** [comment]
I have given up because it seems like OpenVAS/gvm is not compatible with the latest version of Kali. Could you please confirm this?

**Comment by bjoernricks** [comment]
> I have given up because it seems like OpenVAS/gvm is not compatible with the latest version of Kali. Could you please confirm this?

What do you mean?

You can't mix versions from different GVM releases.
https://community.greenbone.net/t/gvm-11-old-stable-initial-release-2019-10-14/3674/4
https://community.greenbone.net/t/gvm-20-08-stable-initial-release-2020-08-12/6312/4

**Comment by cfi-gb** [comment]
I would interpret the question as:

> Is the latest GVM release 20.08 incompatible with Kali?

If this assumption about the question is correct the answer is:

Greenbone doesn't know / has no knowledge about compatibility / incompatibilities with other Linux Distros then the reference system mentioned in https://github.com/greenbone/openvas/blob/v20.8.0/INSTALL.md which is currently Debian 10 (Buster).

Note that your experience might also vary if you build from source or use some packages from 3rdparty repositories which might have some known issues (e.g. see the 3rdparty gvm-setup script problem mentioned in https://community.greenbone.net/t/severity-error-could-not-connect-to-server/5192/20).

**Comment by robsd** [comment]
> I would interpret the question as:
> 
> > Is the latest GVM release 20.08 incompatible with Kali?
> 
> If this assumption about the question is correct the answer is:
> 
> Greenbone doesn't know / has no knowledge about compatibility / incompatibilities with other Linux Distros then the reference system mentioned in https://github.com/greenbone/openvas/blob/v20.8.0/INSTALL.md which is currently Debian 10 (Buster).
> 
> Note that your experience might also vary if you build from source or use some packages from 3rdparty repositories which might have some known issues (e.g. see the 3rdparty gvm-setup script problem mentioned in https://community.greenbone.net/t/severity-error-could-not-connect-to-server/5192/20).

Yes this is what I meant sorry.

I just installed it using `apt-get install openvas` / `apt-get install gvm` and completed the setup using `gvm-setup` but I just get the op's issue whenever I try a scan.

Is there a specific Linux distro you recommend for installing OpenVAS/gvm on? I cannot get the virtual appliance to boot with VirtualBox, I assume that was built using Debian or something?

**Comment by cfi-gb** [comment]
> I just installed it using `apt-get install openvas` / `apt-get install gvm` and completed the setup using `gvm-setup` but I just get the op's issue whenever I try a scan.

This might be the previously mentioned problem in the 3rdparty `gvm-setup` script then:

https://community.greenbone.net/t/severity-error-could-not-connect-to-server/5192/20

I would suggest to contact the maintainer for this script to get any help / fixes.

> Is there a specific Linux distro you recommend for installing OpenVAS/gvm on? I cannot get the virtual appliance to boot with VirtualBox, I assume that was built using Debian or something?

The reference system used by most Greenbone developers and which is also the base of the Greenbone OS is Debian Buster as previously mentioned:

> Greenbone doesn't know / has no knowledge about compatibility / incompatibilities with other Linux Distros then the reference system mentioned in https://github.com/greenbone/openvas/blob/v20.8.0/INSTALL.md which is currently Debian 10 (Buster).

**Comment by bjoernricks** [comment]
> I cannot get the virtual appliance to boot with VirtualBox,

Please follow the instructions at https://community.greenbone.net/t/setting-up-the-greenbone-security-manager-trial-gsm-trial-virtual-machine/6939 and very very important you need to activate the EFI boot option in Virtualbox (Step 13).

**Comment by signasty** [comment]
> @robsd I have deleted your previous comment. A bugtracker is not the place for rants like this, no one is e.g. breaking things on purpose.
> 
> Please try to focus on the actual problem. If you are not getting the exact `died with <Signals.SIGABRT: 6>` message in your logs (you only have posted a screenshot and not much additional info) and the Error in the "Error messages" tab of the report says something about "Failed to connect to scanner" then this is very likely just a setup problem. If this is the case you can find a lot of information on this message and various solution suggestions here:
> 
> https://community.greenbone.net/t/severity-error-could-not-connect-to-server/5192
> 
> If the `died with <Signals.SIGABRT: 6>` happens for you please provide more information on your environment (e.g. origin of your GVM setup like used repositories and similar). This maybe could help to find similarities with the original reporter.

I have just done a clean install using the 20.08 sources from this site. Here is the site that I referenced for the installation.
https://kifarunix.com/install-and-setup-gvm-11-on-ubuntu-20-04/
I am also running Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/44814224/100899251-76de5680-3476-11eb-8242-e2f1115552bb.png)

**Comment by Maselia464** [comment]
> > @robsd I have deleted your previous comment. A bugtracker is not the place for rants like this, no one is e.g. breaking things on purpose.
> > Please try to focus on the actual problem. If you are not getting the exact `died with <Signals.SIGABRT: 6>` message in your logs (you only have posted a screenshot and not much additional info) and the Error in the "Error messages" tab of the report says something about "Failed to connect to scanner" then this is very likely just a setup problem. If this is the case you can find a lot of information on this message and various solution suggestions here:
> > https://community.greenbone.net/t/severity-error-could-not-connect-to-server/5192
> > If the `died with <Signals.SIGABRT: 6>` happens for you please provide more information on your environment (e.g. origin of your GVM setup like used repositories and similar). This maybe could help to find similarities with the original reporter.
> 
> I have just done a clean install using the 20.08 sources from this site. Here is the site that I referenced for the installation.
> https://kifarunix.com/install-and-setup-gvm-11-on-ubuntu-20-04/
> I am also running Ubuntu 20.04.
> 
> ![image](https://user-images.githubusercontent.com/44814224/100899251-76de5680-3476-11eb-8242-e2f1115552bb.png)

Maybe GVM is trying to something that he is not suposed to do ?

Can we have more detail like the system logs or the full system details

Thank in advance

**Comment by jjnicola** [comment]
@signasty @Maselia464 
I think that the error is produced because a wrong [Redis configuration](https://github.com/greenbone/openvas-scanner/blob/master/config/redis-openvas.conf). Please take a look at redis-server, if it is running, if it uses a unix socket, if `db_address` setting inside the openvas.conf configuration file is pointing to the right path (check this with `openvas -s`) and if the ospd-openvas has the right permission to access the socket.
