### ISSUE TITLE
build issue -- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by HaterMonestary** [greenbone/openvas-scanner#657]
Im trying to build on ubuntu running on EC2. 

Ive initially setup a userdata script, tried a few things there to see if I can get it to load in userdata, but its not working for me. I dont have any previous experience in cmake, etc. Ive followed the instructions on the install page so far as how I have understood them, but still no success. I append the cli output, the logfile and the userdata script used to get me this far. 

The CLI output:
`root@ip-10-10-5-23:/home/ubuntu/openvas-scanner/build# cmake ..
-- Configuring the Scanner...
-- Looking for clang-format...
-- Looking for clang-format... /usr/bin/clang-format
Set LIBDIR to /usr/local/lib
-- Install prefix: /usr/local
-- Checking for module 'gnutls>=3.6.4'
--
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  misc/CMakeLists.txt:29 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/openvas-scanner/CMakeFiles/CMakeOutput.log".
root@ip-10-10-5-23:/home/ubuntu/openvas-scanner/build#`

The Logfile:
`root@ip-10-10-5-23:/home/ubuntu/openvas-scanner/build# cat /home/ubuntu/openvas-scanner/CMakeFiles/CMakeOutput.log
The system is: Linux - 4.4.0-1121-aws - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc
Build flags:
Id flags:

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/ubuntu/openvas-scanner/CMakeFiles/3.5.1/CompilerIdC/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_92a86/fast"
/usr/bin/make -f CMakeFiles/cmTC_92a86.dir/build.make CMakeFiles/cmTC_92a86.dir/build
make[1]: Entering directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_92a86.dir/testCCompiler.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_92a86.dir/testCCompiler.c.o   -c /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_92a86
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_92a86.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_92a86.dir/testCCompiler.c.o  -o cmTC_92a86 -rdynamic
make[1]: Leaving directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'

Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e8202/fast"
/usr/bin/make -f CMakeFiles/cmTC_e8202.dir/build.make CMakeFiles/cmTC_e8202.dir/build
make[1]: Entering directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.5/Modules/CMakeCCompilerABI.c
Linking C executable cmTC_e8202
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e8202.dir/link.txt --verbose=1
/usr/bin/cc      -v CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o  -o cmTC_e8202 -rdynamic
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify--enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_e8202' '-rdynamic' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/5/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/cciI44gI.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o cmTC_e8202 /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib-L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o
make[1]: Leaving directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'

Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTC_e8202/fast"]
  ignore line: [/usr/bin/make -f CMakeFiles/cmTC_e8202.dir/build.make CMakeFiles/cmTC_e8202.dir/build]
  ignore line: [make[1]: Entering directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp']
  ignore line: [Building C object CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc     -o CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.5/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTC_e8202]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e8202.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc      -v CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o  -o cmTC_e8202 -rdynamic  ]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/cc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper]
  ignore line: [Target: x86_64-linux-gnu]
  ignore line: [Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/5/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/5/../../../:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_e8202' '-rdynamic' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-linux-gnu/5/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/cciI44gI.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --sysroot=/ --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o cmTC_e8202 /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-linux-gnu/5/crtend.o /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o]
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/cciI44gI.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [--sysroot=/] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-zrelro] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_e8202] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/crtbegin.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/5] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/5]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib]
    arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/5/../../..] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/5/../../..]
    arg [CMakeFiles/cmTC_e8202.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--no-as-needed] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/crtend.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crtn.o] ==> ignore
  remove lib [gcc]
  remove lib [gcc_s]
  remove lib [gcc]
  remove lib [gcc_s]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/5] ==> [/usr/lib/gcc/x86_64-linux-gnu/5]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/5/../../..] ==> [/usr/lib]
  implicit libs: [c]
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/5;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []

Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3a50d/fast"
/usr/bin/make -f CMakeFiles/cmTC_3a50d.dir/build.make CMakeFiles/cmTC_3a50d.dir/build
make[1]: Entering directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_3a50d.dir/feature_tests.c.o
/usr/bin/cc    -std=c11 -o CMakeFiles/cmTC_3a50d.dir/feature_tests.c.o   -c /home/ubuntu/openvas-scanner/CMakeFiles/feature_tests.c
Linking C executable cmTC_3a50d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3a50d.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_3a50d.dir/feature_tests.c.o  -o cmTC_3a50d -rdynamic
make[1]: Leaving directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros

Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_dc35a/fast"
/usr/bin/make -f CMakeFiles/cmTC_dc35a.dir/build.make CMakeFiles/cmTC_dc35a.dir/build
make[1]: Entering directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_dc35a.dir/feature_tests.c.o
/usr/bin/cc    -std=c99 -o CMakeFiles/cmTC_dc35a.dir/feature_tests.c.o   -c /home/ubuntu/openvas-scanner/CMakeFiles/feature_tests.c
Linking C executable cmTC_dc35a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_dc35a.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_dc35a.dir/feature_tests.c.o  -o cmTC_dc35a -rdynamic
make[1]: Leaving directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros

Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_815d2/fast"
/usr/bin/make -f CMakeFiles/cmTC_815d2.dir/build.make CMakeFiles/cmTC_815d2.dir/build
make[1]: Entering directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_815d2.dir/feature_tests.c.o
/usr/bin/cc    -std=c90 -o CMakeFiles/cmTC_815d2.dir/feature_tests.c.o   -c /home/ubuntu/openvas-scanner/CMakeFiles/feature_tests.c
Linking C executable cmTC_815d2
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_815d2.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_815d2.dir/feature_tests.c.o  -o cmTC_815d2 -rdynamic
make[1]: Leaving directory '/home/ubuntu/openvas-scanner/CMakeFiles/CMakeTmp'

    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros
root@ip-10-10-5-23:/home/ubuntu/openvas-scanner/build#`

my userdata script:
`user_data = <<EOF
#!/bin/bash
set -exuo pipefail
sudo apt-get install -y gcc 
sudo apt-get install -y cmake
sudo apt-get install -y make
sudo apt-get install -y clang-format
sudo apt-get install -y pkg-config 
sudo apt-get install -y libssh-gcrypt-dev 
sudo apt-get install -y libgnutls28-dev
sudo apt-get install -y libglib2.0-dev 
sudo apt-get install -y libpcap-dev 
#sudo apt-get install -y libgpgme-dev 
sudo apt-get install -y bison 
sudo apt-get install -y libksba-dev 
sudo apt-get install -y libsnmp-dev
sudo apt-get install -y libgcrypt20-dev 
sudo apt-get install -y redis-server
sudo apt-get update -y
sudo apt-get ugrade -y
cd /home/ubuntu
git clone https://github.com/greenbone/openvas-scanner.git
mkdir /home/ubuntu/openvas-scanner/build
cd /home/ubuntu/openvas-scanner/build
cmake ..
make                # build the scanner
make doc            # build the documentation
make doc-full       # build more developer-oriented documentation
make tests          # build tests
make install        # install the build
make rebuild_cache  # rebuild the cmake cache
cd ..
openvas -s
greenbone-nvt-sync
sudo cp redis-openvas.conf /etc/redis/
sudo chown redis:redis /etc/redis/redis-openvas.conf
sudo echo "db_address = /run/redis-openvas/redis.sock" > /etc/openvas/openvas.conf
sudo systemctl start redis-server@openvas.service`

it does not get to the end before it fails, and it seems it only gets as far as `cmake .. `

**Comment by HaterMonestary** [comment]
sorry the code blocks somehow got messed up by the code content.

**Comment by cfi-gb** [comment]
```
-- Checking for module 'gnutls>=3.6.4'

CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
A required package was not found
```

gnutls (libgnutls28-dev) >= 3.6.4 is required but according to this:

```
--with-pkgversion='Ubuntu 5.4.0-6ubuntu116.04.12' 
```

you're running Ubuntu 16.04 which only provides gnutls (libgnutls28-dev) 3.4.10. I'm closing this as invalid for now as the target system just doesn't provide the prerequisites.

If you need further setup support please join / post at https://community.greenbone.net as this tracker is only used for reporting / handling bugs in GVM.

Thanks for your understanding and help to keep the communication channels clean (bugreports here, support questions at the community portal).
