### ISSUE TITLE
[20.8.1] can't connect to redis while scanning

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#659]
With the last version I get an strange error, when gvmd trigger an scan.
openvas will fails with:
```
sd   main:MESSAGE:2021-02-16 11h37.07 utc:32989: openvas 20.8.1 started
lib  kb:  DEBUG:2021-02-16 11h37.07 utc:32989: fetch_max_db_index: maximum DB number: 16
sd   main:  DEBUG:2021-02-16 11h37.07 utc:32989: Start loading scan preferences.
lib  kb:  DEBUG:2021-02-16 11h37.07 utc:32989: fetch_max_db_index: maximum DB number: 16
sd   main:  DEBUG:2021-02-16 11h37.07 utc:32989: End loading scan preferences.
lib  kb:CRITICAL:2021-02-16 11h37.07 utc:32989: get_redis_ctx: redis connection error to /var/run/redis/redis.soc: No such file or directory
sd   main:WARNING:2021-02-16 11h37.07 utc:32989: WARNING: Cannot connect to KB at '/var/run/redis/redis.sock': Operation not permitted'
```
Two paths for the socket are shown.
openvas -s |grep db_address
shows the correct one:
`db_address = /var/run/redis/redis.sock`
But openvas --update-vt-info will run without any problems.
`lib  kb:  DEBUG:2021-02-16 11h43.47 utc:43811: fetch_max_db_index: maximum DB number: 16`
Only this one line is logged.

Environment:
openvas -V
```
OpenVAS 20.8.1
gvm-libs 20.8.1
```

**Comment by jjnicola** [comment]
Hi @tuxmaster5000,
Check the [redis config file](https://github.com/greenbone/openvas-scanner/blob/master/config/redis-openvas.conf) and adjust the databases option (our default is 1025
)
Also, please try stopping ospd-openvas daemon, flushing redis, and starting ospd-openvas again. 

```
killall ospd-openvas
redis-cli -s /var/run/redis/redis.sock FLUSHALL
ospd-openvas
```

Also, something seems to be wrong, as the following message has wrong socket file name (a missing 'k')
`lib  kb:CRITICAL:2021-02-16 11h37.07 utc:32989: get_redis_ctx: redis connection error to /var/run/redis/redis.soc: No such file or directory`. Check that the socket path in the redis config file and is the same in the openvas.conf.

**Comment by tuxmaster5000** [comment]
Very interesting, exact one charter is truncated.
openvas -s will report this:
```
non_simult_ports = 139, 445, 3389, Services/irc
vendor_version = 
safe_checks = yes
nasl_no_signature_check = no
time_between_request = 0
expand_vhosts = yes
max_checks = 10
optimize_test = yes
report_host_details = yes
cache_folder = /var/cache/openvas
config_file = /etc/openvas/openvas.conf
unscanned_closed_udp = yes
include_folders = /var/lib/greenbone/openvas/plugins
test_empty_vhost = no
plugins_timeout = 320
cgi_path = /cgi-bin:/scripts
checks_read_timeout = 5
unscanned_closed = yes
auto_enable_dependencies = yes
log_whole_attack = no
dumpfile = /var/cache/openvas/openvas.dump
db_address = /var/run/redis/redis.sock
drop_privileges = no
log_plugins_name_at_load = no
scanner_plugins_timeout = 36000
timeout_retry = 3
max_hosts = 30
test_alive_hosts_only = no
open_sock_max_attempts = 5
plugins_folder = /var/lib/greenbone/openvas/plugins

```
But in the logfile, openvas will try to open /var/run/redis/redis.soc

Change the path for testing to /tmp/foo.sock will result in:
openvas -s
```
non_simult_ports = 139, 445, 3389, Services/irc
vendor_version = 
safe_checks = yes
nasl_no_signature_check = no
time_between_request = 0
expand_vhosts = yes
max_checks = 10
optimize_test = yes
report_host_details = yes
cache_folder = /var/cache/openvas
config_file = /etc/openvas/openvas.conf
unscanned_closed_udp = yes
include_folders = /var/lib/greenbone/openvas/plugins
test_empty_vhost = no
plugins_timeout = 320
cgi_path = /cgi-bin:/scripts
checks_read_timeout = 5
unscanned_closed = yes
auto_enable_dependencies = yes
log_whole_attack = no
dumpfile = /var/cache/openvas/openvas.dump
db_address = /tmp/foo.sock
drop_privileges = no
log_plugins_name_at_load = no
scanner_plugins_timeout = 36000
timeout_retry = 3
max_hosts = 30
test_alive_hosts_only = no
open_sock_max_attempts = 5
plugins_folder = /var/lib/greenbone/openvas/plugins
```
And in the log file:
```
lib  kb:CRITICAL:2021-02-18 06h43.29 utc:17238: redis_find: redis connection error to /tmp/foo.sock: No such file or directory
lib  kb:CRITICAL:2021-02-18 06h43.29 utc:17238: get_redis_ctx: redis connection error to /tmp/foo.soc: No such file or directory
```

**Comment by tuxmaster5000** [comment]
As an dirty trick for testing, I add an symlink to the truncated redis path. Then the connection can be established.

**Comment by jjnicola** [comment]
Hi @tuxmaster5000,
as you have been working on this https://github.com/greenbone/gvm-libs/pull/441, maybe you are still linking to the wrong gvm-libs. Try removing the old libraries, remove the build folder and compile both, first the libs and then openvas from scratch. Be sure you don't have modified code. 

https://github.com/greenbone/gvm-libs/pull/441/files#diff-6aa6543a54eb68677c8390331278aeec5c4fcbeddc7d0a59e1f5731f9cba3177R398

**Comment by tuxmaster5000** [comment]
Yes this was it. Thanks, Now I have only added the "#pragma" statements, that the compiler needs.
