### ISSUE TITLE
Login page keeps prompting for credentials 

### ISSUE THREAD

**Issue by ciphermichael** [greenbone/openvas-scanner#662]
Login page keeps timing out and requests for username and password again. This is after the setup.

**Comment by bjoernricks** [comment]
First of all this looks more like a support issue where adding a new topic to https://community.greenbone.net/ would be best and second you are talking about the login at our web application right?

**Comment by cfi-gb** [comment]
Please note that this is no support forum / channel https://raw.githubusercontent.com/greenbone/openvas-scanner/master/.github/ISSUE_TEMPLATE/bug-report.md:

> 1. Be aware that this is not a support forum. If your issue is rather a question than a bug report, please use our community forum at https://community.greenbone.net/c/gse instead.

I'm closing this issue as invalid for now as this is most likely no bug and openvas-scanner also doesn't provide any login page and similar.

Please post a new support question at the community portal.

Thanks for you understanding and help to keep the communication channels clean (bug reports here at github, support questions at the community portal).
