### ISSUE TITLE
[20.8.1]  broken nmap not detected

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#663]
When the nmap binary is available, but broken (for example libblas is missing) then openvas scan will fails with an very unclean error message:
```
sd   main:MESSAGE:2021-02-18 08h55.22 utc:10837: The remote host XXXX is dead
sd   main:MESSAGE:2021-02-18 08h55.22 utc:10837: Vulnerability scan 04092489-8ff5-4e3d-bb2c-065a9952ccd1 finished for host XXXX in 0.07 seconds
sd   main:  DEBUG:2021-02-18 08h55.22 utc:10794: waitpid() failed. No child processes)
sd   main:  DEBUG:2021-02-18 08h55.22 utc:10794: Test complete
```
The messages about the "waitpid and 'is dead" are the result of the broken nmap.
I think an simple test call to 'nmap --version' will be ok as an test for an working nmap tool.

**Comment by cfi-gb** [comment]
nmap is currently called from NASL side to determine the alive status so i'm closing this issue as invalid for the scanner.

The readiness for tools like nmap is already done / available and can be done like described here:

https://community.greenbone.net/t/hint-verify-the-availability-of-scanner-helper-tools-of-your-gse-source-package-installation/1358/3

In addition additional documentation to check why a target isn't alive is available here:

https://community.greenbone.net/t/hint-hosts-are-not-scanned-not-shown-as-alive/332
