### ISSUE TITLE
[5.1.2] most ssh check's fails, because libssh don't support etm MAC hashes.

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/openvas-scanner#68]
For ssh server's that using etm mac hashes only, most of the ssh tests fails, because libssh can't handle etm.
This is also noted [here](https://www.libssh.org/features/)

**Comment by cfi-gb** [comment]
Similar for the key exchange like seen e.g. on libssh2 as well: https://github.com/libssh2/libssh2/issues/41

Not sure what what can be done here on scanner side besides using a different library which probably has the same issue (e.g. libssh2)

Maybe you should create a feature request for the missing functionality in libssh instead?

**Comment by tuxmaster** [comment]
I have add an entry for it in the bug tracker of [libssh](https://bugs.libssh.org/T88).

**Comment by cfi-gb** [comment]
It seems that libssh needs to be build with libnacl for curve25519 key exchange support. At least on Debian this wasn't available up to 0.8.0~20170825.94fa1e38-1 and only the latest 0.8.0~20170825.94fa1e38-2 has now introduced this build dependency:

http://metadata.ftp-master.debian.org/changelogs/main/libs/libssh/libssh_0.8.0~20170825.94fa1e38-2_changelog

With one of the next feed updates the mentioned NVT in https://github.com/greenbone/openvas-scanner/issues/68#issuecomment-384953934 should print additional info about this requirements.

**Comment by cfi-gb** [comment]
Just a quick update:

The new libssh 0.8.0 released last month has introduced chachae20-poly1305 cipher support:

https://www.libssh.org/2018/08/10/libssh-0-8-0/

Furthermore there is a new patch available for libssh to support rsa-sha2-256 and rsa-sha2-512:

https://www.libssh.org/archive/libssh/2018-06/0000047.html

which probably will be included in libssh soon.

Note: An updated version of the features page of libssh seems to already mentioning both as supported:

https://www.libssh.org/features/

But from what i can see in the libssh git that code hasn't landed there yet.

**Comment by kroosec** [comment]
Closing, as this issue is outside the scoop of openvas-scanner but within Libssh'.

**Comment by cfi-gb** [comment]
For the record, libssh 0.9.0 will start to support etm MAC hashes:

https://www.libssh.org/2019/06/28/libssh-0-9-0/
