### ISSUE TITLE
How to scan a host using OMP（openvas-cli）?

### ISSUE THREAD

**Issue by HelloXiaoHe** [greenbone/openvas-scanner#71]
openvas-check-setup --v9

Step 1: Checking OpenVAS Scanner ... 
        OK: OpenVAS Scanner is present in version 5.1.1.
        OK: redis-server is present in version v=4.0.8.
        OK: scanner (kb_location setting) is configured properly using the redis-server socket: /run/redis/redis.sock
        OK: redis-server is running and listening on socket: /run/redis/redis.sock.
        OK: redis-server configuration is OK and redis-server is running.
        OK: NVT collection in /var/lib/openvas/plugins contains 44441 NVTs.
        WARNING: Signature checking of NVTs is not enabled in OpenVAS Scanner.
        SUGGEST: Enable signature checking (see http://www.openvas.org/trusted-nvts.html).
        OK: The NVT cache in /var/cache/openvas contains 52524 files for 44441 NVTs.
Step 2: Checking OpenVAS Manager ... 
        OK: OpenVAS Manager is present in version 7.0.2.
        OK: OpenVAS Manager database found in /var/lib/openvas/mgr/tasks.db.
        OK: Access rights for the OpenVAS Manager database are correct.
        OK: sqlite3 found, extended checks of the OpenVAS Manager installation enabled.
        OK: OpenVAS Manager database is at revision 184.
        OK: OpenVAS Manager expects database at revision 184.
        OK: Database schema is up to date.
        OK: OpenVAS Manager database contains information about 52522 NVTs.
        OK: At least one user exists.
        OK: OpenVAS SCAP database found in /var/lib/openvas/scap-data/scap.db.
        OK: OpenVAS CERT database found in /var/lib/openvas/cert-data/cert.db.
        OK: xsltproc found.
Step 3: Checking user configuration ... 
        WARNING: Your password policy is empty.
        SUGGEST: Edit the /etc/openvas/pwpolicy.conf file to set a password policy.
Step 4: Checking Greenbone Security Assistant (GSA) ... 
        OK: Greenbone Security Assistant is present in version 7.0.2.
        OK: Your OpenVAS certificate infrastructure passed validation.
Step 5: Checking OpenVAS CLI ... 
        OK: OpenVAS CLI version 1.4.5.
Step 6: Checking Greenbone Security Desktop (GSD) ... 
        SKIP: Skipping check for Greenbone Security Desktop.
Step 7: Checking if OpenVAS services are up and running ... 
        OK: netstat found, extended checks of the OpenVAS services enabled.
        OK: OpenVAS Scanner is running and listening on a Unix domain socket.
        OK: OpenVAS Manager is running and listening on a Unix domain socket.
        OK: Greenbone Security Assistant is running and listening on all interfaces.
        OK: Greenbone Security Assistant is listening on port 9392, which is the default port.
Step 8: Checking nmap installation ...
        WARNING: Your version of nmap is not fully supported: 6.47
        SUGGEST: You should install nmap 5.51 if you plan to use the nmap NSE NVTs.
Step 10: Checking presence of optional tools ...
        OK: pdflatex found.
        WARNING: PDF generation failed, most likely due to missing LaTeX packages. The PDF report format will not work.
        SUGGEST: Install required LaTeX packages.
        OK: ssh-keygen found, LSC credential generation for GNU/Linux targets is likely to work.
        OK: rpm found, LSC credential package generation for RPM based targets is likely to work.
        OK: alien found, LSC credential package generation for DEB based targets is likely to work.
        OK: nsis found, LSC credential package generation for Microsoft Windows targets is likely to work.
        OK: SELinux is disabled.

It seems like your OpenVAS-9 installation is OK.

It works well on the web,but when I run like this:

**omp -u admin -w ajcheng --xml='
<create_target>
<name>Test</name>
<hosts>192.168.110.09</hosts>
</create_target>
'**
it return ,**Failed to acquire socket**

**Comment by cfi-gb** [comment]
@HelloXiaoHe Please note the following in the template shown when creating a new issue:

> 2. be aware that this is not a support forum. If you have any questions see http://openvas.org/ for available support options.

Please close this issue and direct your question on how to use OMP/GMP to the users mailinglist.

**Comment by bjoernricks** [comment]
Besides being a question for the mailing list openvas-cli is deprecated and shouldn't be used anymore. Please use https://github.com/greenbone/gvm-tools instead.

**Comment by HelloXiaoHe** [comment]
thanks，I will try it

**Comment by Yashvendra** [comment]
Hi @HelloXiaoHe, next time just enter this `sudo  openvasmd -a 0.0.0.0 -p 9390`, then run your omp commands.

**Comment by bjoernricks** [comment]
> Hi @HelloXiaoHe, next time just enter this `sudo openvasmd -a 0.0.0.0 -p 9390`, then run your omp commands.

Both `openvasmd` and `omp` are deprecated and outdated tools. You should not use them anymore and instead update to a supported release.
