### ISSUE TITLE
[21.4.2] scanner will crash with segfault when running the selftest scan

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/openvas-scanner#825]
### Expected behavior
That the selftest NVT (1.3.6.1.4.1.25623.1.0.810000)

### Actual behavior
The openvas binary crash with segfault

### Steps to reproduce
1. start the scan via the gsa ui

### GVM versions

**gsa:** Greenbone Security Assistant 21.4.1~dev1

**gvm:**
Greenbone Vulnerability Manager 21.4.3
Manager DB revision 242

**openvas:**  
OpenVAS 21.4.2
gvm-libs 21.4.2

**gvm-libs:**   21.4.2

**openvas-smb:** 21.4.0

**ospd-openvas:**
OSP Server for openvas: 21.4.1
OSP: 21.4.1
OSPd OpenVAS: 21.4.1

### Environment

**Operating system:** CentOS 8

**Installation method / source:**  git sources

### Logfiles
No errors on the log files
```
```
I have added the crash dump for it:
[crash.tar.gz](https://github.com/greenbone/openvas-scanner/files/6928884/crash.tar.gz)

**Comment by tuxmaster5000** [comment]
When enable the debug mode of the scanner, I only see this suspect line:
waitpid() failed. No child processes)

> libgvm util:  DEBUG:2021-08-11 11h00.49 utc:2504683: get_redis_ctx: connected to redis:///var/run/redis/redis.sock/3
> sd   main:MESSAGE:2021-08-11 11h00.49 utc:2504682: Vulnerability scan b3dd38e8-28ed-4a17-94e1-2a4cdc9de269 finished for host 127.0.0.1 in 0.04 seconds
> sd   main:MESSAGE:2021-08-11 11h00.49 utc:2504683: Vulnerability scan b3dd38e8-28ed-4a17-94e1-2a4cdc9de269 finished for host ::1 in 0.03 seconds
> libgvm util:  DEBUG:2021-08-11 11h00.49 utc:2504669: redis_delete_all: deleting all elements from KB #4
> sd   main:  DEBUG:2021-08-11 11h00.49 utc:2504669: waitpid() failed. No child processes)
> libgvm util:  DEBUG:2021-08-11 11h00.49 utc:2504669: redis_delete_all: deleting all elements from KB #5
> sd   main:  DEBUG:2021-08-11 11h00.50 utc:2504669: Test complete

**Comment by ArnoStiefvater** [comment]
Thanks a lot for reporting this issue.
Unfortunately I can not reproduce the issue on our reference system debian buster.
I will nonetheless take a short look at it next week.

**Comment by jjnicola** [comment]
Hi @tuxmaster5000, 
Is this issue still happening? I am not able to reproduce it either. 
If it is already fixed, please close it

**Comment by jjnicola** [comment]
For some reason, I can't reproduce it anymore. Will try a bit more. This is one of the backtrace I could see via gdb.
```
Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:461
461	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:461
#1  0x00007f90119c4100 in proctitle_set_args (new_title=0x555be050887e "openvas: testing %s (%s)", args=0x7fff523e9938)
    at /home/juan/dev/gvm-libs/base/proctitle.c:125
#2  0x00007f90119c41c2 in proctitle_set (new_title=0x555be050887e "openvas: testing %s (%s)")
    at /home/juan/dev/gvm-libs/base/proctitle.c:142
#3  0x0000555be05010ae in nasl_thread (args=0x7fff523e9b00) at /home/juan/dev/openvas-scanner/src/nasl_plugins.c:215
#4  0x0000555be0505a9c in create_process (function=0x555be0500f78 <nasl_thread>, argument=0x7fff523e9b00)
    at /home/juan/dev/openvas-scanner/src/processes.c:114
#5  0x0000555be0500f64 in nasl_plugin_launch
    (globals=0x555be0c6f9c0, ip=0x7fff523ea540, vhosts=0x0, kb=0x555be0c865f0, main_kb=0x555be0c96860, oid=0x555be0c91bf0 "1.3.6.1.4.1.25623.1.0.810000") at /home/juan/dev/openvas-scanner/src/nasl_plugins.c:193
#6  0x0000555be05033dd in plugin_launch
    (globals=0x555be0c6f9c0, plugin=0x555be0c77560, ip=0x7fff523ea540, vhosts=0x0, kb=0x555be0c865f0, main_kb=0x555be0c96860, nvti=0x555be0c98e40, error=0x7fff523e9c38) at /home/juan/dev/openvas-scanner/src/pluginlaunch.c:481
#7  0x0000555be04fe2ee in launch_plugin
    (globals=0x555be0c6f9c0, plugin=0x555be0c77560, ip=0x7fff523ea540, vhosts=0x0, kb=0x555be0c865f0, main_kb=0x555be0c96860)
    at /home/juan/dev/openvas-scanner/src/attack.c:606
#8  0x0000555be04fe54a in attack_host
    (globals=0x555be0c6f9c0, ip=0x7fff523ea540, vhosts=0x0, sched=0x555be0c974b0, kb=0x555be0c865f0, main_kb=0x555be0c96860)
--Type <RET> for more, q to quit, c to continue without paging--
   e/juan/dev/openvas-scanner/src/attack.c:673
#9  0x0000555be04fefb9 in attack_start (args=0x7fff523ea620) at /home/juan/dev/openvas-scanner/src/attack.c:958
#10 0x0000555be0505a9c in create_process (function=0x555be04fec85 <attack_start>, argument=0x7fff523ea620)
    at /home/juan/dev/openvas-scanner/src/processes.c:114
#11 0x0000555be04ffba3 in attack_network (globals=0x555be0c6f9c0) at /home/juan/dev/openvas-scanner/src/attack.c:1367
#12 0x0000555be0502475 in openvas (argc=1, argv=0x7fff523ea978) at /home/juan/dev/openvas-scanner/src/openvas.c:603
#13 0x0000555be0500a91 in main (argc=3, argv=0x7fff523ea978) at /home/juan/dev/openvas-scanner/src/main.c:40
(gdb) 
```

**Comment by ArnoStiefvater** [comment]
We have made quite some changes in places which seem to be the origin of this issue although we were not able to reproduce or verify it.
Do you still get the segfault with up to date old-stable (21.4.x) or stable (22.4.0, new release, [install doc](https://greenbone.github.io/docs/latest/)) branch?

**Comment by tuxmaster5000** [comment]
On 21.4.4 I can't see the crash again. So it looks like it is fixed.
