### ISSUE TITLE
task gets stuck at 98% and the status is stopped

### ISSUE THREAD

**Issue by HelloXiaoHe** [greenbone/openvas-scanner#94]
### Expected behavior
scan the task complete at 100% and status is Done
### Current behavior
the task gets stuck at 98%,and the status is stopped,restart or resume task donesnt work 

### Steps to reproduce
1.create target
2.create task
3.start task

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 7.0.2

**gvm:** (gvmd --version)
gvm-cli 1.3.1

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.1
**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**
Linux version 3.10.0-327.28.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Aug 3 11:11:39 UTC 2016
**Installation method / source:** (packages, source installation)

### Logfiles

```
I find the log in /var/log/openvas/openvasmd.log

manage:WARNING:2018-05-06 19h56.01 utc:97193: sql_exec_internal: sqlite3_step failed: database disk image is malformed
md manage:WARNING:2018-05-06 19h56.01 utc:97193: sqlv: sql_exec_internal failed
md manage:WARNING:2018-05-06 19h56.03 utc:97193: sql_close: attempt to close db with open statement(s)
md manage:WARNING:2018-05-07 08h50.46 UTC:25201: sql_close: attempt to close db with open statement(s)
md manage:WARNING:2018-05-08 07h32.50 UTC:7226: sql_close: attempt to close db with open statement(s)
md
```
![default](https://user-images.githubusercontent.com/23098688/39861964-dfc6d3aa-5474-11e8-9965-f83a8522ee58.png)

**Comment by cfi-gb** [comment]
@HelloXiaoHe It looks like you're using outdated components of the OpenVAS framework. Please always update to the latest available versions like outlined in your filled issue template:

> 1. make sure that you're using the latest published GVM components for the release you are using: http://openvas.org/install-source.html.

This avoids that you're causing work of developers / contributors where the issue might be already solved / not happening in the newer releases.

**Comment by HelloXiaoHe** [comment]
@cfi-gb thanks  for your reply and sorry about that
few tutorials I find on the Internet ,I met some problem
so I create an issue ,but I dont realize that causing work for you.
is there any way to get more information?

I install openvas with OpenVAS Binary Packages 
yum install -y wget bzip2 texlive net-tools alien gnutls-utils
wget -q -O - https://www.atomicorp.com/installers/atomic | sh
yum install openvas
....
But I dont know how to update the version,
Is there a easy way to update it

**Comment by jjnicola** [comment]
Hello @HelloXiaoHe,
this last question is proper for the openvas-discuss mailing list http://lists.wald.intevation.org/cgi-bin/mailman/listinfo/openvas-discuss.
Close issue here.
